create or replace view htn__define_dx_existing as select * from (values
('http://hl7.org/fhir/sid/icd-10-cm', 'I10', 'Essential (primary) hypertension')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.011', 'Pre-existing essential hypertension complicating pregnancy, first trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.012', 'Pre-existing essential hypertension complicating pregnancy, second trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.013', 'Pre-existing essential hypertension complicating pregnancy, third trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.019', 'Pre-existing essential hypertension complicating pregnancy, unspecified trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.02', 'Pre-existing essential hypertension complicating childbirth')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.03', 'Pre-existing essential hypertension complicating the puerperium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.111', 'Pre-existing hypertensive heart disease complicating pregnancy, first trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.112', 'Pre-existing hypertensive heart disease complicating pregnancy, second trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.113', 'Pre-existing hypertensive heart disease complicating pregnancy, third trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.119', 'Pre-existing hypertensive heart disease complicating pregnancy, unspecified trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.12', 'Pre-existing hypertensive heart disease complicating childbirth')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.13', 'Pre-existing hypertensive heart disease complicating the puerperium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.211', 'Pre-existing hypertensive chronic kidney disease complicating pregnancy, first trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.212', 'Pre-existing hypertensive chronic kidney disease complicating pregnancy, second trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.213', 'Pre-existing hypertensive chronic kidney disease complicating pregnancy, third trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.219', 'Pre-existing hypertensive chronic kidney disease complicating pregnancy, unspecified trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.22', 'Pre-existing hypertensive chronic kidney disease complicating childbirth')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.23', 'Pre-existing hypertensive chronic kidney disease complicating the puerperium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.311', 'Pre-existing hypertensive heart and chronic kidney disease complicating pregnancy, first trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.312', 'Pre-existing hypertensive heart and chronic kidney disease complicating pregnancy, second trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.313', 'Pre-existing hypertensive heart and chronic kidney disease complicating pregnancy, third trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.319', 'Pre-existing hypertensive heart and chronic kidney disease complicating pregnancy, unspecified trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.32', 'Pre-existing hypertensive heart and chronic kidney disease complicating childbirth')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.33', 'Pre-existing hypertensive heart and chronic kidney disease complicating the puerperium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.411', 'Pre-existing secondary hypertension complicating pregnancy, first trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.412', 'Pre-existing secondary hypertension complicating pregnancy, second trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.413', 'Pre-existing secondary hypertension complicating pregnancy, third trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.419', 'Pre-existing secondary hypertension complicating pregnancy, unspecified trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.42', 'Pre-existing secondary hypertension complicating childbirth')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.43', 'Pre-existing secondary hypertension complicating the puerperium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.911', 'Unspecified pre-existing hypertension complicating pregnancy, first trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.912', 'Unspecified pre-existing hypertension complicating pregnancy, second trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.913', 'Unspecified pre-existing hypertension complicating pregnancy, third trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.919', 'Unspecified pre-existing hypertension complicating pregnancy, unspecified trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.92', 'Unspecified pre-existing hypertension complicating childbirth')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.93', 'Unspecified pre-existing hypertension complicating the puerperium')
,('http://snomed.info/sct', '111438007', 'Hypertension secondary to renal disease in obstetric context (disorder)')
,('http://snomed.info/sct', '18416000', 'Essential hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '198942000', 'Benign essential hypertension complicating pregnancy, childbirth and the puerperium (disorder)')
,('http://snomed.info/sct', '198944004', 'Benign essential hypertension complicating pregnancy, childbirth and the puerperium - delivered (disorder)')
,('http://snomed.info/sct', '198945003', 'Benign essential hypertension complicating pregnancy, childbirth and the puerperium - delivered with postnatal complication (disorder)')
,('http://snomed.info/sct', '198946002', 'Benign essential hypertension complicating pregnancy, childbirth and the puerperium - not delivered (disorder)')
,('http://snomed.info/sct', '198947006', 'Benign essential hypertension complicating pregnancy, childbirth and the puerperium with postnatal complication (disorder)')
,('http://snomed.info/sct', '199005000', 'Pre-existing hypertension complicating pregnancy, childbirth and puerperium (disorder)')
,('http://snomed.info/sct', '199007008', 'Pre-existing hypertensive heart and renal disease complicating pregnancy, childbirth and the puerperium (disorder)')
,('http://snomed.info/sct', '23717007', 'Benign essential hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '24042004', 'Chronic hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '26078007', 'Hypertension secondary to renal disease complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '29259002', 'Malignant hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '31407004', 'Pre-existing hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '34694006', 'Pre-existing hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '35303009', 'Benign essential hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '367390009', 'Hypertension in the obstetric context (disorder)')
,('http://snomed.info/sct', '37618003', 'Chronic hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '39727004', 'Hypertension secondary to renal disease complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '40511000119107', 'Postpartum pre-existing essential hypertension (disorder)')
,('http://snomed.info/sct', '48552006', 'Hypertension secondary to renal disease complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '63287004', 'Benign essential hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '65402008', 'Pre-existing hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '71874008', 'Benign essential hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '72022006', 'Essential hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '78808002', 'Essential hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '81626002', 'Malignant hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '8218002', 'Chronic hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '86041002', 'Pre-existing hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '8762007', 'Chronic hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '9901000', 'Essential hypertension complicating AND/OR reason for care during puerperium (disorder)')
) AS t (system, code, display) ;