create or replace view htn__define_rx as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1000001', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011710', 'aliskiren 150 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011713', 'aliskiren 150 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011718', 'aliskiren 150 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011729', 'aliskiren 300 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011736', 'aliskiren 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011739', 'aliskiren 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011750', 'aliskiren 300 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011753', 'aliskiren 300 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1013930', '12 HR clonidine hydrochloride 0.1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1013937', '12 HR clonidine hydrochloride 0.2 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104220', 'furosemide 4 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104222', 'bumetanide 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104223', 'bumetanide 0.5 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104230', 'spironolactone 1 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104231', 'spironolactone 2 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104232', 'spironolactone 5 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104233', 'spironolactone 10 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104245', 'benzthiazide 25 MG / triamterene 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104248', 'chlorthalidone 50 MG / triamterene 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104308', 'atenolol 0.5 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104357', 'methyldopa 250 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104370', 'captopril 25 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1050798', 'aliskiren 150 MG / amlodipine 5 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1050803', 'aliskiren 300 MG / amlodipine 10 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1050806', 'aliskiren 300 MG / amlodipine 10 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1050809', 'aliskiren 300 MG / amlodipine 5 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1050812', 'aliskiren 300 MG / amlodipine 5 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1091646', 'azilsartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1091652', 'azilsartan medoxomil 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1092566', '{7 (24 HR guanfacine 1 MG Extended Release Oral Tablet) / 7 (24 HR guanfacine 2 MG Extended Release Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1111439', '24 HR hydrochlorothiazide 25 MG / metoprolol tartrate 200 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191185', 'penbutolol sulfate 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1234256', '4 ML labetalol hydrochloride 5 MG/ML Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235144', 'azilsartan medoxomil 40 MG / chlorthalidone 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235151', 'azilsartan medoxomil 40 MG / chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1241888', 'tolazoline 100 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1251903', 'ethacrynic acid 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1251907', 'ethacrynic acid 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1297753', 'betaxolol hydrochloride 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1297757', 'betaxolol hydrochloride 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299859', 'hydrochlorothiazide 12.5 MG / moexipril hydrochloride 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299871', 'hydrochlorothiazide 12.5 MG / moexipril hydrochloride 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299890', 'hydrochlorothiazide 25 MG / moexipril hydrochloride 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299896', 'moexipril hydrochloride 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299897', 'moexipril hydrochloride 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1361019', '1.7 ML phentolamine mesylate 0.235 MG/ML Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1361023', 'phentolamine mesylate 5 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '141902', 'lacidipine 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '141903', 'lacidipine 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1423767', 'nimodipine 3 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1435624', 'enalapril maleate 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1495058', 'propranolol hydrochloride 4.28 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '150751', 'oxprenolol 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '150752', 'phenoxybenzamine 50 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '152916', 'atenolol 50 MG / chlorthalidone 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153077', 'valsartan 40 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153155', 'atenolol 25 MG / bendroflumethiazide 1.25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153680', 'lercanidipine 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153822', 'candesartan cilexetil 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153823', 'candesartan cilexetil 8 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1593725', 'sotalol hydrochloride 5 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1600716', 'amlodipine 10 MG / perindopril arginine 14 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1600724', 'amlodipine 2.5 MG / perindopril arginine 3.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1600728', 'amlodipine 5 MG / perindopril arginine 7 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1606347', 'metoprolol tartrate 37.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1606349', 'metoprolol tartrate 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1665057', '2 ML verapamil hydrochloride 2.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1665061', '4 ML verapamil hydrochloride 2.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719286', '10 ML furosemide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719290', '2 ML furosemide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719291', '4 ML furosemide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1727569', '4 ML bumetanide 0.25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1727572', '2 ML bumetanide 0.25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1729200', '1 ML enalaprilat 1.25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1729205', '2 ML enalaprilat 1.25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1729521', '2 ML torsemide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1729527', '5 ML torsemide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736541', '250 ML esmolol hydrochloride 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736546', '10 ML esmolol hydrochloride 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1744259', '5 ML metoprolol tartrate 1 MG/ML Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790239', '50 ML clevidipine 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790245', '100 ML clevidipine 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790247', '250 ML clevidipine 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791229', '5 ML diltiazem hydrochloride 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791232', '10 ML diltiazem hydrochloride 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791233', '25 ML diltiazem hydrochloride 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791240', 'diltiazem hydrochloride 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1798281', 'nebivolol 5 MG / valsartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1806884', 'lisinopril 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812011', 'Osmotic 24 HR nifedipine 30 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812013', 'Osmotic 24 HR nifedipine 60 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812015', 'Osmotic 24 HR nifedipine 90 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1876368', '100 ML sodium nitroprusside 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1922720', 'Atrial Fibrillation sotalol hydrochloride 120 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1922763', 'Atrial Fibrillation sotalol hydrochloride 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1922765', 'Atrial Fibrillation sotalol hydrochloride 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1923422', 'sotalol hydrochloride 120 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1923424', 'sotalol hydrochloride 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1923426', 'sotalol hydrochloride 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197361', 'amlodipine 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197379', 'atenolol 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197380', 'atenolol 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197381', 'atenolol 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197382', 'atenolol 100 MG / chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197383', 'atenolol 50 MG / chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197394', 'bendroflumethiazide 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197417', 'bumetanide 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197418', 'bumetanide 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197419', 'bumetanide 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197436', 'captopril 25 MG / hydrochlorothiazide 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197437', 'captopril 25 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197438', 'captopril 50 MG / hydrochlorothiazide 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197439', 'captopril 50 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197475', 'chlorothiazide 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197476', 'chlorothiazide 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197477', 'chlorothiazide 500 MG / reserpine 0.125 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197498', 'chlorthalidone 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197499', 'chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197500', 'chlorthalidone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197625', 'doxazosin 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197626', 'doxazosin 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197627', 'doxazosin 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197628', 'doxazosin 8 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197730', 'furosemide 10 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197731', 'furosemide 8 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197732', 'furosemide 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197743', 'guanabenz 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197744', 'guanabenz 8 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197745', 'guanfacine 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197746', 'guanfacine 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197770', 'hydrochlorothiazide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197771', 'hydrochlorothiazide 50 MG / reserpine 0.125 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197788', 'hydroflumethiazide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197815', 'indapamide 1.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197816', 'indapamide 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197848', 'isradipine 2.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197849', 'isradipine 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197884', 'lisinopril 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197885', 'hydrochlorothiazide 12.5 MG / lisinopril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197886', 'hydrochlorothiazide 12.5 MG / lisinopril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197887', 'hydrochlorothiazide 25 MG / lisinopril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197950', 'methyclothiazide 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197951', 'methyclothiazide 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197952', 'deserpidine 0.5 MG / methyclothiazide 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197953', 'deserpidine 0.25 MG / methyclothiazide 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197954', 'methyclothiazide 2.5 MG / reserpine 0.1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197955', 'methyldopa 125 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197956', 'methyldopa 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197958', 'methyldopa 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197959', 'chlorothiazide 250 MG / methyldopa 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197960', 'hydrochlorothiazide 25 MG / methyldopa 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197961', 'hydrochlorothiazide 50 MG / methyldopa 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197962', 'hydrochlorothiazide 30 MG / methyldopa 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197963', 'hydrochlorothiazide 15 MG / methyldopa 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197977', 'metolazone 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197978', 'metolazone 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197979', 'metolazone 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197986', 'minoxidil 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197987', 'minoxidil 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198000', 'bendroflumethiazide 5 MG / nadolol 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198001', 'bendroflumethiazide 5 MG / nadolol 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198004', 'nadolol 120 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198005', 'nadolol 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198006', 'nadolol 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198007', 'nadolol 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198008', 'nadolol 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198032', 'nifedipine 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198033', 'nifedipine 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198034', '24 HR nifedipine 30 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198035', '24 HR nifedipine 60 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198036', '24 HR nifedipine 90 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198037', 'nimodipine 30 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198104', 'pindolol 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198105', 'pindolol 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198110', 'polythiazide 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198111', 'polythiazide 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198112', 'polythiazide 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198141', 'prazosin 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198188', 'ramipril 2.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198189', 'ramipril 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198194', 'Rauwolfia serpentina (USP) 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198195', 'Rauwolfia serpentina (USP) 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198196', 'reserpine 0.1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198197', 'reserpine 0.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198222', 'spironolactone 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198223', 'spironolactone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198224', 'hydrochlorothiazide 25 MG / spironolactone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198225', 'hydrochlorothiazide 50 MG / spironolactone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198284', 'timolol 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198285', 'timolol 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198286', 'timolol 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198312', 'triamterene 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198313', 'triamterene 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198314', 'hydrochlorothiazide 25 MG / triamterene 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198316', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198319', 'trichlormethiazide 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198369', 'torsemide 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198370', 'torsemide 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198371', 'torsemide 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198372', 'torsemide 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199277', 'pindolol 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199329', 'nifedipine 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199351', 'trandolapril 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199352', 'trandolapril 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199353', 'trandolapril 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199491', 'nimodipine 0.2 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199494', 'oxprenolol 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199495', 'oxprenolol 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199610', 'furosemide 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199622', 'trandolapril 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199707', 'cilazapril 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199708', 'cilazapril 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199709', 'cilazapril 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199717', 'clopamide 5 MG / pindolol 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199753', 'guanethidine 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199757', 'isradipine 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199776', 'minoxidil 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199783', 'nimodipine 30 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199786', 'oxprenolol 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199787', 'oxprenolol 160 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199791', 'phentolamine 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199796', 'prazosin 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199797', 'prazosin 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199798', 'prazosin 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199799', 'prazosin 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199816', 'trandolapril 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199817', 'trandolapril 2 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199850', 'valsartan 80 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199903', 'hydrochlorothiazide 12.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999031', '24 HR metoprolol succinate 100 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999033', '24 HR metoprolol succinate 200 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999035', '24 HR metoprolol succinate 25 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999037', '24 HR metoprolol succinate 50 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999185', '50 ML sodium nitroprusside 0.2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199919', 'valsartan 160 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199937', 'cilazapril 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200031', 'carvedilol 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200032', 'carvedilol 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200033', 'carvedilol 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200094', 'irbesartan 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200095', 'irbesartan 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200096', 'irbesartan 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200284', 'hydrochlorothiazide 12.5 MG / valsartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200285', 'hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '204154', 'furosemide 50 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '204452', '5 ML methyldopate hydrochloride 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '204501', 'hydrochlorothiazide 25 MG / reserpine 0.125 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2047715', 'amlodipine 2.5 MG / celecoxib 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2047716', 'amlodipine 5 MG / celecoxib 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2047717', 'amlodipine 10 MG / celecoxib 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052423', '100 ML sodium nitroprusside 0.2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205304', 'telmisartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205305', 'telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205326', 'lisinopril 30 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2057152', 'telmisartan 10 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '227058', '24 HR nifedipine 30 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '227059', '24 HR nifedipine 60 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '237192', 'chlorothiazide 250 MG / reserpine 0.125 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240793', '2 ML sodium nitroprusside 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '246399', 'furosemide 20 MG / spironolactone 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '248657', 'furosemide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '248708', '12 HR nifedipine 10 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249620', '12 HR nifedipine 20 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250044', 'torsemide 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250206', '12 HR nifedipine 10 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250376', 'hydroflumethiazide 25 MG / spironolactone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250377', 'hydroflumethiazide 50 MG / spironolactone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250384', '24 HR nifedipine 40 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250543', 'bendroflumethiazide 2.5 MG / timolol 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250546', 'moxonidine 0.4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250547', 'moxonidine 0.2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250553', 'cyclopenthiazide 0.25 MG / oxprenolol 160 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250660', 'bumetanide 0.2 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250708', 'furosemide 40 MG / triamterene 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '251308', 'furosemide 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '251856', 'ramipril 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '251857', 'ramipril 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260376', 'terazosin 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261962', 'ramipril 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '282486', 'bumetanide 0.25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '282755', 'telmisartan 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283316', 'hydrochlorothiazide 12.5 MG / telmisartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283317', 'hydrochlorothiazide 12.5 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308135', 'amlodipine 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308136', 'amlodipine 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308962', 'captopril 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308963', 'captopril 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308964', 'captopril 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309198', 'chlorothiazide 50 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310139', 'eprosartan 400 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310140', 'eprosartan 600 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310429', 'furosemide 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310662', 'guanadrel 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310664', 'guanethidine 10 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310665', 'guanethidine 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310666', 'guanethidine 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310792', 'hydrochlorothiazide 12.5 MG / irbesartan 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310793', 'hydrochlorothiazide 12.5 MG / irbesartan 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310796', 'hydrochlorothiazide 12.5 MG / quinapril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310797', 'hydrochlorothiazide 12.5 MG / quinapril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310798', 'hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310809', 'hydrochlorothiazide 25 MG / quinapril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310811', 'hydrochlorothiazide 25 MG / timolol 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310812', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310818', 'hydrochlorothiazide 50 MG / triamterene 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311353', 'lisinopril 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311354', 'lisinopril 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311671', 'metolazone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311983', '24 HR nisoldipine 10 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311984', '24 HR nisoldipine 20 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311985', '24 HR nisoldipine 30 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312481', 'polythiazide 0.5 MG / prazosin 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312482', 'polythiazide 0.5 MG / prazosin 2 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312483', 'polythiazide 0.5 MG / prazosin 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312593', 'prazosin 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312594', 'prazosin 2 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312748', 'quinapril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312749', 'quinapril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312750', 'quinapril 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313096', 'spironolactone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313214', 'terazosin 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313215', 'terazosin 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313216', 'terazosin 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313217', 'terazosin 2 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313219', 'terazosin 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313988', 'furosemide 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314029', 'hydrochlorothiazide 25 MG / triamterene 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314076', 'lisinopril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314077', 'lisinopril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314203', 'quinapril 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317173', 'captopril 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349199', 'valsartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349200', 'valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349201', 'valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349353', 'hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349373', 'olmesartan medoxomil 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349401', 'olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349405', 'olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349483', 'valsartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351256', 'eplerenone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351257', 'eplerenone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351258', 'eplerenone 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351292', 'eprosartan 600 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351293', 'eprosartan 600 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360344', '24 HR nisoldipine 40 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '387013', 'nebivolol 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '388078', 'moxonidine 0.3 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '389180', 'felodipine 2.5 MG / ramipril 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '389181', 'felodipine 5 MG / ramipril 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '389182', 'imidapril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '389183', 'imidapril 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '389184', 'imidapril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '389185', 'eprosartan 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '391901', 'nifedipine 60 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '391980', 'nifedipine 30 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '393275', 'atenolol 50 MG / nifedipine 20 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '401965', 'ramipril 1.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '401968', 'ramipril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '401971', 'olmesartan medoxomil 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402695', '24 HR felodipine 10 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402696', '24 HR felodipine 5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402698', '24 HR felodipine 2.5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403853', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403854', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403855', 'hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404011', 'amlodipine 5 MG / atorvastatin 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404013', 'amlodipine 10 MG / atorvastatin 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '411434', 'trandolapril 4 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '411759', '24 HR trandolapril 2 MG / verapamil hydrochloride 180 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '429503', 'hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '431610', 'bumetanide 0.5 MG / potassium chloride 573 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '431740', 'bendroflumethiazide 2.5 MG / potassium chloride 630 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '431741', 'bendroflumethiazide 2.5 MG / potassium chloride 573 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '433844', '24 HR indapamide 1.5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '477130', 'hydrochlorothiazide 25 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '484152', 'chlorothiazide 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '485471', 'hydrochlorothiazide 25 MG / irbesartan 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562518', '24 HR isradipine 10 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562520', '24 HR isradipine 5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '577776', 'candesartan cilexetil 16 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '578325', 'candesartan cilexetil 16 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '578330', 'candesartan cilexetil 32 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597967', 'amlodipine 10 MG / atorvastatin 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597971', 'amlodipine 2.5 MG / atorvastatin 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597974', 'amlodipine 2.5 MG / atorvastatin 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597977', 'amlodipine 5 MG / atorvastatin 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597980', 'amlodipine 5 MG / atorvastatin 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597984', 'amlodipine 5 MG / atorvastatin 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597987', 'amlodipine 10 MG / atorvastatin 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597990', 'amlodipine 10 MG / atorvastatin 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597993', 'amlodipine 2.5 MG / atorvastatin 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '617325', 'ethacrynate sodium 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '630032', 'furosemide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636042', 'hydrochlorothiazide 12.5 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636045', 'hydrochlorothiazide 25 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636360', '24 HR doxazosin 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636361', '24 HR doxazosin 8 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '639536', 'candesartan cilexetil 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '639537', 'candesartan cilexetil 32 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '686924', 'carvedilol 3.125 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '722126', 'amlodipine 10 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '722131', 'amlodipine 10 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '722134', 'amlodipine 5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '722137', 'amlodipine 5 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727574', '10 ML furosemide 10 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727575', '4 ML furosemide 10 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '730861', 'amlodipine 10 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '730866', 'amlodipine 10 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '730869', 'amlodipine 5 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '730872', 'amlodipine 5 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '751612', 'nebivolol 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '751618', 'nebivolol 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '755528', 'atenolol 5 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '757674', 'amlodipine 10 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '757675', 'amlodipine 2.5 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '757676', 'amlodipine 5 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763519', '24 HR nisoldipine 17 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763574', '24 HR nisoldipine 25.5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763589', '24 HR nisoldipine 34 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '790489', '24 HR nisoldipine 8.5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '797029', '{7 (terazosin 1 MG Oral Tablet) / 7 (terazosin 2 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '802749', 'candesartan cilexetil 32 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '827073', 'nebivolol 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830795', '24 HR diltiazem hydrochloride 360 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830801', '24 HR diltiazem hydrochloride 300 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830837', '24 HR diltiazem hydrochloride 240 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830845', '24 HR diltiazem hydrochloride 180 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830861', '24 HR diltiazem hydrochloride 120 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830865', '12 HR diltiazem hydrochloride 60 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830869', '12 HR diltiazem hydrochloride 90 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830872', '12 HR diltiazem hydrochloride 120 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830874', '24 HR diltiazem hydrochloride 120 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830877', '24 HR diltiazem hydrochloride 180 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830879', '24 HR diltiazem hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830882', '24 HR diltiazem hydrochloride 300 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830897', '24 HR diltiazem hydrochloride 360 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830900', '24 HR diltiazem hydrochloride 420 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '831012', 'diltiazem hydrochloride 60 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '831054', 'diltiazem hydrochloride 120 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '831102', 'diltiazem hydrochloride 90 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '831103', 'diltiazem hydrochloride 60 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '831359', '24 HR diltiazem hydrochloride 420 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '833217', 'diltiazem hydrochloride 30 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '833237', 'diltiazem hydrochloride 180 MG / enalapril maleate 5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '833707', '12 HR diltiazem hydrochloride 60 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845488', 'ramipril 1.25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848131', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848135', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848140', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848145', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848151', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '849860', 'diltiazem malate 240 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854901', 'bisoprolol fumarate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854905', 'bisoprolol fumarate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854908', 'bisoprolol fumarate 10 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854916', 'bisoprolol fumarate 2.5 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854919', 'bisoprolol fumarate 5 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854925', 'perindopril erbumine 8 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854984', 'perindopril erbumine 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854988', 'perindopril erbumine 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854993', 'indapamide 1.25 MG / perindopril erbumine 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856422', 'hydrochlorothiazide 25 MG / propranolol hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856429', 'hydrochlorothiazide 25 MG / propranolol hydrochloride 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856443', '1 ML propranolol hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856448', 'propranolol hydrochloride 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856457', 'propranolol hydrochloride 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856460', '24 HR propranolol hydrochloride 120 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856481', '24 HR propranolol hydrochloride 160 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856519', 'propranolol hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856535', '24 HR propranolol hydrochloride 60 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856556', 'propranolol hydrochloride 60 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856569', '24 HR propranolol hydrochloride 80 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856578', 'propranolol hydrochloride 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856615', 'bendroflumethiazide 2.5 MG / propranolol hydrochloride 80 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856616', 'bendroflumethiazide 5 MG / propranolol hydrochloride 160 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856703', 'propranolol hydrochloride 10 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856704', 'propranolol hydrochloride 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856712', 'propranolol hydrochloride 16 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856713', 'propranolol hydrochloride 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856719', 'propranolol hydrochloride 2 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856724', 'propranolol hydrochloride 4 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856733', 'propranolol hydrochloride 8 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856735', 'propranolol hydrochloride 80 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856737', 'propranolol hydrochloride 80 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856739', 'propranolol hydrochloride 90 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857166', 'fosinopril sodium 10 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857174', 'fosinopril sodium 20 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857183', 'fosinopril sodium 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857187', 'fosinopril sodium 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858580', '12 HR nicardipine hydrochloride 45 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858587', '12 HR nicardipine hydrochloride 30 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858599', '200 ML nicardipine hydrochloride 0.1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858603', '200 ML nicardipine hydrochloride 0.2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858607', '10 ML nicardipine hydrochloride 2.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858613', 'nicardipine hydrochloride 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858616', 'nicardipine hydrochloride 30 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858804', 'enalapril maleate 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858810', 'enalapril maleate 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858813', 'enalapril maleate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858817', 'enalapril maleate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858821', 'enalapril maleate 1.25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858824', 'enalapril maleate 5 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858828', 'enalapril maleate 10 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858921', 'enalapril maleate 20 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860510', '24 HR carvedilol phosphate 10 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860516', '24 HR carvedilol phosphate 20 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860522', '24 HR carvedilol phosphate 40 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860532', '24 HR carvedilol phosphate 80 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '861402', 'phenoxybenzamine hydrochloride 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '862006', '24 HR guanfacine 1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '862013', '24 HR guanfacine 2 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '862019', '24 HR guanfacine 3 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '862025', '24 HR guanfacine 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '865154', 'bisoprolol fumarate 1.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '865155', 'bisoprolol fumarate 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '865157', 'bisoprolol fumarate 3.75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '865159', 'bisoprolol fumarate 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866412', '24 HR metoprolol succinate 100 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866419', '24 HR metoprolol succinate 200 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866427', '24 HR metoprolol succinate 25 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866436', '24 HR metoprolol succinate 50 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866452', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 100 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866461', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 25 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866472', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 50 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866479', 'hydrochlorothiazide 25 MG / metoprolol tartrate 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866482', 'hydrochlorothiazide 25 MG / metoprolol tartrate 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866491', 'hydrochlorothiazide 50 MG / metoprolol tartrate 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866508', '5 ML metoprolol tartrate 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866511', 'metoprolol tartrate 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866514', 'metoprolol tartrate 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866924', 'metoprolol tartrate 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '876514', 'amlodipine 10 MG / telmisartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '876519', 'amlodipine 10 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '876524', 'amlodipine 5 MG / telmisartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '876529', 'amlodipine 5 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884173', 'clonidine hydrochloride 0.1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884185', 'clonidine hydrochloride 0.2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884189', 'clonidine hydrochloride 0.3 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884192', 'chlorthalidone 15 MG / clonidine hydrochloride 0.1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884198', 'chlorthalidone 15 MG / clonidine hydrochloride 0.2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884203', 'chlorthalidone 15 MG / clonidine hydrochloride 0.3 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '885878', '24 HR clonidine hydrochloride 0.1 MG/ML Extended Release Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '892791', 'clonidine hydrochloride 0.025 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '892793', 'clonidine hydrochloride 0.15 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '892795', 'clonidine hydrochloride 0.25 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896758', 'labetalol hydrochloride 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896762', 'labetalol hydrochloride 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896766', 'labetalol hydrochloride 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896771', 'labetalol hydrochloride 5 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896976', 'hydrochlorothiazide 25 MG / labetalol hydrochloride 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896983', 'labetalol hydrochloride 400 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897584', '24 HR verapamil hydrochloride 100 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897590', '24 HR verapamil hydrochloride 200 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897596', '24 HR verapamil hydrochloride 300 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897612', '24 HR verapamil hydrochloride 120 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897618', '24 HR verapamil hydrochloride 180 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897624', '24 HR verapamil hydrochloride 240 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897630', '24 HR verapamil hydrochloride 360 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897640', 'verapamil hydrochloride 180 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897649', 'verapamil hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897659', 'verapamil hydrochloride 120 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897666', 'verapamil hydrochloride 120 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897683', 'verapamil hydrochloride 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897722', 'verapamil hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897781', '24 HR trandolapril 1 MG / verapamil hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897783', '24 HR trandolapril 2 MG / verapamil hydrochloride 180 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897844', '24 HR trandolapril 2 MG / verapamil hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897853', '24 HR trandolapril 4 MG / verapamil hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898316', '4 ML verapamil hydrochloride 2.5 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898340', 'verapamil hydrochloride 180 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898342', 'amlodipine 10 MG / benazepril hydrochloride 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898346', 'amlodipine 10 MG / benazepril hydrochloride 40 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898350', 'amlodipine 2.5 MG / benazepril hydrochloride 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898353', 'amlodipine 5 MG / benazepril hydrochloride 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898356', 'amlodipine 5 MG / benazepril hydrochloride 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898359', 'amlodipine 5 MG / benazepril hydrochloride 40 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898362', 'benazepril hydrochloride 10 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898367', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898372', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898378', 'benazepril hydrochloride 5 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898687', 'benazepril hydrochloride 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898690', 'benazepril hydrochloride 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898719', 'benazepril hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898723', 'benazepril hydrochloride 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '901438', 'verapamil hydrochloride 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '901446', 'verapamil hydrochloride 240 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '901450', 'verapamil hydrochloride 8 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '904589', 'sotalol hydrochloride 240 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '904622', 'sotalol hydrochloride 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '904630', '10 ML sotalol hydrochloride 15 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '904632', 'sotalol hydrochloride 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '904634', 'sotalol hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905199', 'hydralazine hydrochloride 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905203', 'hydralazine hydrochloride 100 MG / hydrochlorothiazide 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905211', 'hydralazine hydrochloride 25 MG / hydrochlorothiazide 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905217', 'hydralazine hydrochloride 50 MG / hydrochlorothiazide 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905222', 'hydralazine hydrochloride 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905225', 'hydralazine hydrochloride 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905353', 'hydralazine hydrochloride 25 MG / hydrochlorothiazide 15 MG / reserpine 0.1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905377', 'hydralazine hydrochloride 37.5 MG / isosorbide dinitrate 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905395', 'hydralazine hydrochloride 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '966571', '1 ML hydralazine hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977880', 'amiloride hydrochloride 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977883', 'amiloride hydrochloride 5 MG / hydrochlorothiazide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977887', 'amiloride hydrochloride 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977890', 'amiloride hydrochloride 10 MG / furosemide 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977907', 'amiloride hydrochloride 2.5 MG / cyclopenthiazide 0.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977920', 'amiloride hydrochloride 2.5 MG / atenolol 50 MG / hydrochlorothiazide 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977945', 'amiloride hydrochloride 2.5 MG / furosemide 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977949', 'amiloride hydrochloride 2.5 MG / hydrochlorothiazide 25 MG / timolol maleate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977950', 'amiloride hydrochloride 2.5 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977951', 'amiloride hydrochloride 5 MG / bumetanide 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977959', 'amiloride hydrochloride 5 MG / furosemide 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '978577', 'carteolol hydrochloride 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '978581', 'carteolol hydrochloride 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979432', '100 ML esmolol hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979436', 'esmolol hydrochloride 250 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979464', 'hydrochlorothiazide 12.5 MG / losartan potassium 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979468', 'hydrochlorothiazide 12.5 MG / losartan potassium 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979471', 'hydrochlorothiazide 25 MG / losartan potassium 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979480', 'losartan potassium 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979485', 'losartan potassium 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979492', 'losartan potassium 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998685', 'acebutolol 400 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998689', 'acebutolol 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998693', 'acebutolol 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998694', 'acebutolol 200 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998695', 'acebutolol 400 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999967', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999986', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999991', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999996', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet')
) AS t (system, code, display) ;