create or replace view htn__define_enc_hospice as select * from (values
('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9687', 'Hospice services provided to patient any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9688', 'Patients using hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9690', 'Patient receiving hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9691', 'Patient had hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9692', 'Hospice services received by patient any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9693', 'Patient use of hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9694', 'Hospice services utilized by patient any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9700', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9702', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9707', 'Patient received hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9709', 'Hospice services used by patient any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9710', 'Patient was provided hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9713', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9714', 'Patient is using hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9715', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9718', 'Hospice services for patient provided any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9720', 'Hospice services for patient occurred any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9723', 'Hospice services for patient received any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9725', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9740', 'Hospice services given to patient any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9741', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9758', 'Patient in hospice and in terminal phase')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9760', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9761', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9768', 'Patients who utilize hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9802', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9805', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9809', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9819', 'Patients who use hospice services any time during the measurement period')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9857', 'Patient admitted to hospice')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9860', 'Patient spent less than three days in hospice care')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9861', 'Patient spent greater than or equal to three days in hospice care')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5003', 'Hospice care provided in nursing long term care facility (ltc) or non-skilled nursing facility (nf)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5004', 'Hospice care provided in skilled nursing facility (snf)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5005', 'Hospice care provided in inpatient hospital')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5006', 'Hospice care provided in inpatient hospice facility')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5007', 'Hospice care provided in long term care facility')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5008', 'Hospice care provided in inpatient psychiatric facility')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5010', 'Hospice home care provided in a hospice facility')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9473', 'Services performed by chaplain in the hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9474', 'Services performed by dietary counselor in the hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9475', 'Services performed by other counselor in the hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9476', 'Services performed by volunteer in the hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9477', 'Services performed by care coordinator in the hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9478', 'Services performed by other qualified therapist in the hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9479', 'Services performed by qualified pharmacist in the hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5003', 'Hospice care provided in nursing long term care facility (ltc) or non-skilled nursing facility (nf)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5004', 'Hospice care provided in skilled nursing facility (snf)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5005', 'Hospice care provided in inpatient hospital')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5006', 'Hospice care provided in inpatient hospice facility')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5007', 'Hospice care provided in long term care facility')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5008', 'Hospice care provided in inpatient psychiatric facility')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'Q5010', 'Hospice home care provided in a hospice facility')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S9126', 'Hospice care, in the home, per diem')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T2042', 'Hospice routine home care. per diem')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T2043', 'Hospice continuous home care. per hour')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T2044', 'Hospice inpatient respite care. per diem')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T2045', 'Hospice general inpatient care. per diem')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T2046', 'Hospice long term care, room and board only. per diem')
) AS t (system, code, display) ;