create or replace view htn__define_dx as select * from
(VALUES
     ('http://hl7.org/fhir/sid/icd-10-cm', 'I10',   'Primary essential hypertension')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I11',   'Hypertensive heart disease')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I11.0', 'Hypertensive heart disease w heart failure')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I11.9', 'Hypertensive heart disease w/o heart failure')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I12',   'Hypertensive CKD')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.0', 'Hypertensive CKD stage 5 or ESRD')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.9', 'Hypertensive CKD stage 1-4')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I13',   'Hypertensive heart and CKD')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.0', 'Hypertensive heart and CKD stage 1-4')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.1', 'Hypertensive heart and CKD w/o heart failure')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.10','Hypertensive heart and CKD stage 1-4 w/o heart failure')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.11','Hypertensive heart and CKD stage 5 w/o heart failure')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.2', 'Hypertensive heart and CKD stage 5 or ESRD')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I15',   'Secondary HTN')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I15.0', 'Renovascular HTN')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I15.1', 'HTN secondary to other renal disorder')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I15.2', 'HTN secondary to other endocrine disorder')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I15.8', 'HTN Secondary to other')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'I15.9', 'HTN Secondary to unspecified')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'O10',   'Pre-existing HTN heart complicating pregnancy')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.1', 'Pre-existing HTN heart complicating pregnancy')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.11', 'Pre-existing HTN heart complicating pregnancy')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.111', 'Pre-existing HTN heart complicating pregnancy 1st trimester')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.112', 'Pre-existing HTN heart complicating pregnancy 2nd trimester')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.113', 'Pre-existing HTN heart complicating pregnancy 3rd trimester')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.119', 'Pre-existing HTN heart complicating pregnancy NOS trimester')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.12', 'Pre-existing HTN heart complicating childbirth')
    ,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.13', 'Pre-existing HTN heart complicating puerperium')
) AS t (system, code, display)
;