create or replace view htn__define_frailty as select * from (values
('http://www.ama-assn.org/go/cpt', '99504', 'Home visit for mechanical ventilation care')
,('http://www.ama-assn.org/go/cpt', '99509', 'Home visit for assistance with activities of daily living and personal care')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.000', 'Pressure ulcer of unspecified elbow, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.001', 'Pressure ulcer of unspecified elbow, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.002', 'Pressure ulcer of unspecified elbow, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.003', 'Pressure ulcer of unspecified elbow, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.004', 'Pressure ulcer of unspecified elbow, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.006', 'Pressure-induced deep tissue damage of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.009', 'Pressure ulcer of unspecified elbow, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.010', 'Pressure ulcer of right elbow, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.011', 'Pressure ulcer of right elbow, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.012', 'Pressure ulcer of right elbow, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.013', 'Pressure ulcer of right elbow, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.014', 'Pressure ulcer of right elbow, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.016', 'Pressure-induced deep tissue damage of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.019', 'Pressure ulcer of right elbow, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.020', 'Pressure ulcer of left elbow, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.021', 'Pressure ulcer of left elbow, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.022', 'Pressure ulcer of left elbow, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.023', 'Pressure ulcer of left elbow, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.024', 'Pressure ulcer of left elbow, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.026', 'Pressure-induced deep tissue damage of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.029', 'Pressure ulcer of left elbow, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.100', 'Pressure ulcer of unspecified part of back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.101', 'Pressure ulcer of unspecified part of back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.102', 'Pressure ulcer of unspecified part of back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.103', 'Pressure ulcer of unspecified part of back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.104', 'Pressure ulcer of unspecified part of back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.106', 'Pressure-induced deep tissue damage of unspecified part of back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.109', 'Pressure ulcer of unspecified part of back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.110', 'Pressure ulcer of right upper back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.111', 'Pressure ulcer of right upper back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.112', 'Pressure ulcer of right upper back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.113', 'Pressure ulcer of right upper back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.114', 'Pressure ulcer of right upper back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.116', 'Pressure-induced deep tissue damage of right upper back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.119', 'Pressure ulcer of right upper back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.120', 'Pressure ulcer of left upper back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.121', 'Pressure ulcer of left upper back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.122', 'Pressure ulcer of left upper back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.123', 'Pressure ulcer of left upper back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.124', 'Pressure ulcer of left upper back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.126', 'Pressure-induced deep tissue damage of left upper back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.129', 'Pressure ulcer of left upper back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.130', 'Pressure ulcer of right lower back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.131', 'Pressure ulcer of right lower back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.132', 'Pressure ulcer of right lower back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.133', 'Pressure ulcer of right lower back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.134', 'Pressure ulcer of right lower back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.136', 'Pressure-induced deep tissue damage of right lower back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.139', 'Pressure ulcer of right lower back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.140', 'Pressure ulcer of left lower back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.141', 'Pressure ulcer of left lower back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.142', 'Pressure ulcer of left lower back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.143', 'Pressure ulcer of left lower back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.144', 'Pressure ulcer of left lower back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.146', 'Pressure-induced deep tissue damage of left lower back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.149', 'Pressure ulcer of left lower back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.150', 'Pressure ulcer of sacral region, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.151', 'Pressure ulcer of sacral region, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.152', 'Pressure ulcer of sacral region, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.153', 'Pressure ulcer of sacral region, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.154', 'Pressure ulcer of sacral region, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.156', 'Pressure-induced deep tissue damage of sacral region')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.159', 'Pressure ulcer of sacral region, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.200', 'Pressure ulcer of unspecified hip, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.201', 'Pressure ulcer of unspecified hip, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.202', 'Pressure ulcer of unspecified hip, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.203', 'Pressure ulcer of unspecified hip, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.204', 'Pressure ulcer of unspecified hip, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.206', 'Pressure-induced deep tissue damage of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.209', 'Pressure ulcer of unspecified hip, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.210', 'Pressure ulcer of right hip, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.211', 'Pressure ulcer of right hip, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.212', 'Pressure ulcer of right hip, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.213', 'Pressure ulcer of right hip, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.214', 'Pressure ulcer of right hip, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.216', 'Pressure-induced deep tissue damage of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.219', 'Pressure ulcer of right hip, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.220', 'Pressure ulcer of left hip, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.221', 'Pressure ulcer of left hip, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.222', 'Pressure ulcer of left hip, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.223', 'Pressure ulcer of left hip, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.224', 'Pressure ulcer of left hip, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.226', 'Pressure-induced deep tissue damage of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.229', 'Pressure ulcer of left hip, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.300', 'Pressure ulcer of unspecified buttock, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.301', 'Pressure ulcer of unspecified buttock, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.302', 'Pressure ulcer of unspecified buttock, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.303', 'Pressure ulcer of unspecified buttock, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.304', 'Pressure ulcer of unspecified buttock, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.306', 'Pressure-induced deep tissue damage of unspecified buttock')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.309', 'Pressure ulcer of unspecified buttock, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.310', 'Pressure ulcer of right buttock, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.311', 'Pressure ulcer of right buttock, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.312', 'Pressure ulcer of right buttock, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.313', 'Pressure ulcer of right buttock, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.314', 'Pressure ulcer of right buttock, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.316', 'Pressure-induced deep tissue damage of right buttock')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.319', 'Pressure ulcer of right buttock, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.320', 'Pressure ulcer of left buttock, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.321', 'Pressure ulcer of left buttock, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.322', 'Pressure ulcer of left buttock, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.323', 'Pressure ulcer of left buttock, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.324', 'Pressure ulcer of left buttock, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.326', 'Pressure-induced deep tissue damage of left buttock')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.329', 'Pressure ulcer of left buttock, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.40', 'Pressure ulcer of contiguous site of back, buttock and hip, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.41', 'Pressure ulcer of contiguous site of back, buttock and hip, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.42', 'Pressure ulcer of contiguous site of back, buttock and hip, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.43', 'Pressure ulcer of contiguous site of back, buttock and hip, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.44', 'Pressure ulcer of contiguous site of back, buttock and hip, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.45', 'Pressure ulcer of contiguous site of back, buttock and hip, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.46', 'Pressure-induced deep tissue damage of contiguous site of back, buttock and hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.500', 'Pressure ulcer of unspecified ankle, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.501', 'Pressure ulcer of unspecified ankle, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.502', 'Pressure ulcer of unspecified ankle, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.503', 'Pressure ulcer of unspecified ankle, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.504', 'Pressure ulcer of unspecified ankle, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.506', 'Pressure-induced deep tissue damage of unspecified ankle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.509', 'Pressure ulcer of unspecified ankle, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.510', 'Pressure ulcer of right ankle, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.511', 'Pressure ulcer of right ankle, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.512', 'Pressure ulcer of right ankle, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.513', 'Pressure ulcer of right ankle, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.514', 'Pressure ulcer of right ankle, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.516', 'Pressure-induced deep tissue damage of right ankle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.519', 'Pressure ulcer of right ankle, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.520', 'Pressure ulcer of left ankle, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.521', 'Pressure ulcer of left ankle, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.522', 'Pressure ulcer of left ankle, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.523', 'Pressure ulcer of left ankle, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.524', 'Pressure ulcer of left ankle, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.526', 'Pressure-induced deep tissue damage of left ankle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.529', 'Pressure ulcer of left ankle, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.600', 'Pressure ulcer of unspecified heel, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.601', 'Pressure ulcer of unspecified heel, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.602', 'Pressure ulcer of unspecified heel, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.603', 'Pressure ulcer of unspecified heel, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.604', 'Pressure ulcer of unspecified heel, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.606', 'Pressure-induced deep tissue damage of unspecified heel')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.609', 'Pressure ulcer of unspecified heel, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.610', 'Pressure ulcer of right heel, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.611', 'Pressure ulcer of right heel, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.612', 'Pressure ulcer of right heel, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.613', 'Pressure ulcer of right heel, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.614', 'Pressure ulcer of right heel, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.616', 'Pressure-induced deep tissue damage of right heel')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.619', 'Pressure ulcer of right heel, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.620', 'Pressure ulcer of left heel, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.621', 'Pressure ulcer of left heel, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.622', 'Pressure ulcer of left heel, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.623', 'Pressure ulcer of left heel, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.624', 'Pressure ulcer of left heel, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.626', 'Pressure-induced deep tissue damage of left heel')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.629', 'Pressure ulcer of left heel, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.810', 'Pressure ulcer of head, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.811', 'Pressure ulcer of head, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.812', 'Pressure ulcer of head, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.813', 'Pressure ulcer of head, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.814', 'Pressure ulcer of head, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.816', 'Pressure-induced deep tissue damage of head')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.819', 'Pressure ulcer of head, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.890', 'Pressure ulcer of other site, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.891', 'Pressure ulcer of other site, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.892', 'Pressure ulcer of other site, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.893', 'Pressure ulcer of other site, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.894', 'Pressure ulcer of other site, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.896', 'Pressure-induced deep tissue damage of other site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.899', 'Pressure ulcer of other site, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.90', 'Pressure ulcer of unspecified site, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.91', 'Pressure ulcer of unspecified site, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.92', 'Pressure ulcer of unspecified site, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.93', 'Pressure ulcer of unspecified site, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.94', 'Pressure ulcer of unspecified site, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.95', 'Pressure ulcer of unspecified site, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.96', 'Pressure-induced deep tissue damage of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M62.50', 'Muscle wasting and atrophy, not elsewhere classified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M62.81', 'Muscle weakness (generalized)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M62.84', 'Sarcopenia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.0XXA', 'Fall on same level from slipping, tripping and stumbling without subsequent striking against object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.0XXD', 'Fall on same level from slipping, tripping and stumbling without subsequent striking against object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.0XXS', 'Fall on same level from slipping, tripping and stumbling without subsequent striking against object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.10XA', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.10XD', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.10XS', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.110A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against sharp glass, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.110D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against sharp glass, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.110S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against sharp glass, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.111A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against power tool or machine, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.111D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against power tool or machine, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.111S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against power tool or machine, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.118A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other sharp object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.118D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other sharp object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.118S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other sharp object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.119A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified sharp object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.119D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified sharp object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.119S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified sharp object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.190A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against furniture, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.190D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against furniture, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.190S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against furniture, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.198A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.198D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.198S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W06.XXXA', 'Fall from bed, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W06.XXXD', 'Fall from bed, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W06.XXXS', 'Fall from bed, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W07.XXXA', 'Fall from chair, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W07.XXXD', 'Fall from chair, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W07.XXXS', 'Fall from chair, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W08.XXXA', 'Fall from other furniture, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W08.XXXD', 'Fall from other furniture, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W08.XXXS', 'Fall from other furniture, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.0XXA', 'Fall (on)(from) escalator, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.0XXD', 'Fall (on)(from) escalator, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.0XXS', 'Fall (on)(from) escalator, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.1XXA', 'Fall (on)(from) sidewalk curb, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.1XXD', 'Fall (on)(from) sidewalk curb, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.1XXS', 'Fall (on)(from) sidewalk curb, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.2XXA', 'Fall (on)(from) incline, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.2XXD', 'Fall (on)(from) incline, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.2XXS', 'Fall (on)(from) incline, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.8XXA', 'Fall (on) (from) other stairs and steps, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.8XXD', 'Fall (on) (from) other stairs and steps, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.8XXS', 'Fall (on) (from) other stairs and steps, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.9XXA', 'Fall (on) (from) unspecified stairs and steps, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.9XXD', 'Fall (on) (from) unspecified stairs and steps, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.9XXS', 'Fall (on) (from) unspecified stairs and steps, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.00XA', 'Striking against unspecified object with subsequent fall, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.00XD', 'Striking against unspecified object with subsequent fall, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.00XS', 'Striking against unspecified object with subsequent fall, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.02XA', 'Striking against glass with subsequent fall, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.02XD', 'Striking against glass with subsequent fall, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.02XS', 'Striking against glass with subsequent fall, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.09XA', 'Striking against other object with subsequent fall, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.09XD', 'Striking against other object with subsequent fall, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.09XS', 'Striking against other object with subsequent fall, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.11XA', 'Fall from or off toilet without subsequent striking against object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.11XD', 'Fall from or off toilet without subsequent striking against object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.11XS', 'Fall from or off toilet without subsequent striking against object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.12XA', 'Fall from or off toilet with subsequent striking against object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.12XD', 'Fall from or off toilet with subsequent striking against object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.12XS', 'Fall from or off toilet with subsequent striking against object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.2XXA', 'Fall in (into) shower or empty bathtub, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.2XXD', 'Fall in (into) shower or empty bathtub, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.2XXS', 'Fall in (into) shower or empty bathtub, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.30XA', 'Fall on same level, unspecified, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.30XD', 'Fall on same level, unspecified, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.30XS', 'Fall on same level, unspecified, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.31XA', 'Fall on same level due to stepping on an object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.31XD', 'Fall on same level due to stepping on an object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.31XS', 'Fall on same level due to stepping on an object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.39XA', 'Other fall on same level, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.39XD', 'Other fall on same level, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.39XS', 'Other fall on same level, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W19.XXXA', 'Unspecified fall, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W19.XXXD', 'Unspecified fall, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W19.XXXS', 'Unspecified fall, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Y92.199', 'Unspecified place in other specified residential institution as the place of occurrence of the external cause')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z59.3', 'Problems related to living in residential institution')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z73.6', 'Limitation of activities due to disability')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.01', 'Bed confinement status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.09', 'Other reduced mobility')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.1', 'Need for assistance with personal care')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.2', 'Need for assistance at home and no other household member able to render care')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.3', 'Need for continuous supervision')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.8', 'Other problems related to care provider dependency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.9', 'Problem related to care provider dependency, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z91.81', 'History of falling')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.11', 'Dependence on respirator [ventilator] status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.3', 'Dependence on wheelchair')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.81', 'Dependence on supplemental oxygen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.89', 'Dependence on other enabling machines and devices')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0162', 'Skilled services by a registered nurse (rn) for management and evaluation of the plan of care; each 15 minutes (the patient's underlying condition or complication requires an rn to ensure that essential non-skilled care achieves its purpose in the home health or hospice setting)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0299', 'Direct skilled nursing services of a registered nurse (rn) in the home health or hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0300', 'Direct skilled nursing services of a licensed practical nurse (lpn) in the home health or hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0493', 'Skilled services of a registered nurse (rn) for the observation and assessment of the patient's condition, each 15 minutes (the change in the patient's condition requires skilled nursing personnel to identify and evaluate the patient's need for possible modification of treatment in the home health or hospice setting)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0494', 'Skilled services of a licensed practical nurse (lpn) for the observation and assessment of the patient's condition, each 15 minutes (the change in the patient's condition requires skilled nursing personnel to identify and evaluate the patient's need for possible modification of treatment in the home health or hospice setting)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S0271', 'Physician management of patient home care, hospice monthly case rate (per 30 days)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S0311', 'Comprehensive management and care coordination for advanced illness, per calendar month')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S9123', 'Nursing care, in the home; by registered nurse, per hour (use for general nursing care only, not to be used when cpt codes 99500-99602 can be used)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S9124', 'Nursing care, in the home; by licensed practical nurse, per hour')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1000', 'Private duty / independent nursing service(s) - licensed, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1001', 'Nursing assessment / evaluation')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1002', 'Rn services, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1003', 'Lpn/lvn services, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1004', 'Services of a qualified nursing aide, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1005', 'Respite care services, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1019', 'Personal care services, per 15 minutes, not for an inpatient or resident of a hospital, nursing facility, icf/mr or imd, part of the individualized plan of treatment (code may not be used to identify services provided by home health aide or certified nurse assistant)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1020', 'Personal care services, per diem, not for an inpatient or resident of a hospital, nursing facility, icf/mr or imd, part of the individualized plan of treatment (code may not be used to identify services provided by home health aide or certified nurse assistant)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1021', 'Home health aide or certified nurse assistant, per visit')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1022', 'Contracted home health agency services, all services provided under contract, per day')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1030', 'Nursing care, in the home, by registered nurse, per diem')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1031', 'Nursing care, in the home, by licensed practical nurse, per diem')
,('http://snomed.info/sct', '10637031000119106', 'Pressure ulcer of buttock stage 1 (disorder)')
,('http://snomed.info/sct', '10637071000119109', 'Pressure ulcer of buttock stage 2 (disorder)')
,('http://snomed.info/sct', '10637111000119102', 'Pressure ulcer of buttock stage 3 (disorder)')
,('http://snomed.info/sct', '10637151000119101', 'Pressure ulcer of buttock stage 4 (disorder)')
,('http://snomed.info/sct', '129588001', 'Adult failure to thrive syndrome (disorder)')
,('http://snomed.info/sct', '138371000119104', 'Paresis as late effect of poliomyelitis (disorder)')
,('http://snomed.info/sct', '162845004', 'On examination - failure to thrive (disorder)')
,('http://snomed.info/sct', '16728003', 'Inherited spastic paresis (disorder)')
,('http://snomed.info/sct', '17886000', 'Fall from wheelchair (event)')
,('http://snomed.info/sct', '20902002', 'Fall from bed (event)')
,('http://snomed.info/sct', '214436006', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting (event)')
,('http://snomed.info/sct', '214437002', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, driver of motor vehicle injured (event)')
,('http://snomed.info/sct', '214438007', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, passenger of motor vehicle injured (event)')
,('http://snomed.info/sct', '214439004', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, motor cyclist injured (event)')
,('http://snomed.info/sct', '214441003', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, occupant of tram injured (event)')
,('http://snomed.info/sct', '214442005', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, rider of animal or occupant of animal-drawn vehicle injured (event)')
,('http://snomed.info/sct', '214443000', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, pedal cyclist injured (event)')
,('http://snomed.info/sct', '214444006', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, pedestrian injured (event)')
,('http://snomed.info/sct', '217082002', 'Accidental fall (event)')
,('http://snomed.info/sct', '217083007', 'Fall on or from stairs or steps (event)')
,('http://snomed.info/sct', '217084001', 'Fall on or from escalator (event)')
,('http://snomed.info/sct', '217086004', 'Fall from escalator (event)')
,('http://snomed.info/sct', '217088003', 'Fall on or from stairs (event)')
,('http://snomed.info/sct', '217090002', 'Fall from stairs (event)')
,('http://snomed.info/sct', '217092005', 'Fall on or from steps (event)')
,('http://snomed.info/sct', '217093000', 'Fall on steps (event)')
,('http://snomed.info/sct', '217094006', 'Fall from steps (event)')
,('http://snomed.info/sct', '217142006', 'Fall from chair or bed (event)')
,('http://snomed.info/sct', '217154006', 'Fall on same level from slipping, tripping or stumbling (event)')
,('http://snomed.info/sct', '217155007', 'Fall on same level from slipping (event)')
,('http://snomed.info/sct', '217156008', 'Fall on same level from tripping (event)')
,('http://snomed.info/sct', '217157004', 'Fall on same level from stumbling (event)')
,('http://snomed.info/sct', '217158009', 'Fall on moving sidewalk (event)')
,('http://snomed.info/sct', '217173005', 'Fall from bump against object (event)')
,('http://snomed.info/sct', '225558004', 'Pressure ulcer of back (disorder)')
,('http://snomed.info/sct', '225562005', 'Pressure ulcer of sacral region (disorder)')
,('http://snomed.info/sct', '225563000', 'Pressure ulcer of buttock (disorder)')
,('http://snomed.info/sct', '242109009', 'Fall down stairs of motor bus while boarding or alighting (event)')
,('http://snomed.info/sct', '242389003', 'Fall due to wet surface (event)')
,('http://snomed.info/sct', '242390007', 'Fall due to polished surface (event)')
,('http://snomed.info/sct', '242391006', 'Fall due to discarded object (event)')
,('http://snomed.info/sct', '242392004', 'Fall in bath or shower (event)')
,('http://snomed.info/sct', '242395002', 'Fall due to trip on loose carpet (event)')
,('http://snomed.info/sct', '242396001', 'Fall due to uneven surface indoors (event)')
,('http://snomed.info/sct', '242413007', 'Fall from furniture (event)')
,('http://snomed.info/sct', '242414001', 'Fall from stool (event)')
,('http://snomed.info/sct', '242419006', 'Fall from toilet seat (event)')
,('http://snomed.info/sct', '269699007', 'Fall on same level from impact against object (event)')
,('http://snomed.info/sct', '274918000', 'Fall on same level due to nature of surface (event)')
,('http://snomed.info/sct', '33036003', 'Fall on same level (event)')
,('http://snomed.info/sct', '40104005', 'Fall in home (event)')
,('http://snomed.info/sct', '414188008', 'Fall down stairs (event)')
,('http://snomed.info/sct', '414189000', 'Fall down steps (event)')
,('http://snomed.info/sct', '414190009', 'Fall on stairs (event)')
,('http://snomed.info/sct', '427849003', 'Fall on hard surface (event)')
,('http://snomed.info/sct', '428484005', 'Organic failure to thrive (disorder)')
,('http://snomed.info/sct', '429621003', 'Fall on concrete (event)')
,('http://snomed.info/sct', '44188002', 'Fall in shower (event)')
,('http://snomed.info/sct', '459821000124104', 'McArdle sign (finding)')
,('http://snomed.info/sct', '52702003', 'Chronic fatigue syndrome (disorder)')
,('http://snomed.info/sct', '56307009', 'Fall from table (event)')
,('http://snomed.info/sct', '67223001', 'Fall on escalator (event)')
,('http://snomed.info/sct', '699214007', 'Pressure ulcer of hip (disorder)')
,('http://snomed.info/sct', '699215008', 'Pressure ulcer of lower back (disorder)')
,('http://snomed.info/sct', '699216009', 'Pressure ulcer of coccygeal region (disorder)')
,('http://snomed.info/sct', '699218005', 'Pressure ulcer of upper back (disorder)')
,('http://snomed.info/sct', '715504003', 'Spastic paraparesis co-occurrent with deafness (disorder)')
,('http://snomed.info/sct', '74541001', 'Fall from bench (event)')
,('http://snomed.info/sct', '763829004', 'Oculopharyngodistal myopathy (disorder)')
,('http://snomed.info/sct', '823018004', 'Muscle paresis due to and following neuromuscular blockade (disorder)')
,('http://snomed.info/sct', '83468000', 'Fall from chair (event)')
,('http://snomed.info/sct', '8960001000004106', 'Pressure ulcer of skin of right ischial tuberosity region (disorder)')
,('http://snomed.info/sct', '90619006', 'Fall in bathtub (event)')
,('http://snomed.info/sct', '92341000119107', 'Weakness of extremities as sequela of stroke (disorder)')
) AS t (system, code, display) ;