-- See also NLM ValueSet
-- https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.600.1476

-- TODO: potentially missing rxnorm codes for brand-names and generics?
-- 29046 Lisinopril
-- 1546022 Lisinopril anhydrous
-- 203644 Prinivil
-- 1178276 Prinivil Pill
-- 206764 Lisinopril 5 MG Oral Tablet [Prinivil]

create or replace view htn__define_rx as select * from (values
 ('http://www.nlm.nih.gov/research/umls/rxnorm', '1000001', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011710', 'aliskiren 150 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011713', 'aliskiren 150 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011736', 'aliskiren 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011739', 'aliskiren 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011750', 'aliskiren 300 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011753', 'aliskiren 300 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1013930', '12 HR clonidine hydrochloride 0.1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1013937', '12 HR clonidine hydrochloride 0.2 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104232', 'spironolactone 5 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1091646', 'azilsartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1091652', 'azilsartan medoxomil 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1092566', '{7 (24 HR guanfacine 1 MG Extended Release Oral Tablet) / 7 (24 HR guanfacine 2 MG Extended Release Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1234256', '4 ML labetalol hydrochloride 5 MG/ML Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235144', 'azilsartan medoxomil 40 MG / chlorthalidone 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235151', 'azilsartan medoxomil 40 MG / chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1297753', 'betaxolol hydrochloride 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1297757', 'betaxolol hydrochloride 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299859', 'hydrochlorothiazide 12.5 MG / moexipril hydrochloride 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299871', 'hydrochlorothiazide 12.5 MG / moexipril hydrochloride 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299890', 'hydrochlorothiazide 25 MG / moexipril hydrochloride 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299896', 'moexipril hydrochloride 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299897', 'moexipril hydrochloride 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1435624', 'enalapril maleate 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1495058', 'propranolol hydrochloride 4.28 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153822', 'candesartan cilexetil 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153823', 'candesartan cilexetil 8 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1600716', 'amlodipine 10 MG / perindopril arginine 14 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1600724', 'amlodipine 2.5 MG / perindopril arginine 3.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1600728', 'amlodipine 5 MG / perindopril arginine 7 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1606347', 'metoprolol tartrate 37.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1606349', 'metoprolol tartrate 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1656340', 'sacubitril 24 MG / valsartan 26 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1656349', 'sacubitril 49 MG / valsartan 51 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1656354', 'sacubitril 97 MG / valsartan 103 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1665057', '2 ML verapamil hydrochloride 2.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1665061', '4 ML verapamil hydrochloride 2.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719286', '10 ML furosemide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719290', '2 ML furosemide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719291', '4 ML furosemide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1727569', '4 ML bumetanide 0.25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1727572', '2 ML bumetanide 0.25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1729200', '1 ML enalaprilat 1.25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1729205', '2 ML enalaprilat 1.25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1744259', '5 ML metoprolol tartrate 1 MG/ML Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790239', '50 ML clevidipine 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790245', '100 ML clevidipine 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790247', '250 ML clevidipine 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791229', '5 ML diltiazem hydrochloride 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791232', '10 ML diltiazem hydrochloride 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791233', '25 ML diltiazem hydrochloride 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791240', 'diltiazem hydrochloride 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1798281', 'nebivolol 5 MG / valsartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1806884', 'lisinopril 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812011', 'Osmotic 24 HR nifedipine 30 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812013', 'Osmotic 24 HR nifedipine 60 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812015', 'Osmotic 24 HR nifedipine 90 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197361', 'amlodipine 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197379', 'atenolol 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197380', 'atenolol 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197381', 'atenolol 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197382', 'atenolol 100 MG / chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197383', 'atenolol 50 MG / chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197417', 'bumetanide 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197418', 'bumetanide 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197419', 'bumetanide 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197436', 'captopril 25 MG / hydrochlorothiazide 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197437', 'captopril 25 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197438', 'captopril 50 MG / hydrochlorothiazide 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197439', 'captopril 50 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197475', 'chlorothiazide 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197476', 'chlorothiazide 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197499', 'chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197500', 'chlorthalidone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197625', 'doxazosin 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197626', 'doxazosin 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197627', 'doxazosin 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197628', 'doxazosin 8 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197730', 'furosemide 10 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197731', 'furosemide 8 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197732', 'furosemide 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197745', 'guanfacine 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197746', 'guanfacine 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197770', 'hydrochlorothiazide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197815', 'indapamide 1.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197816', 'indapamide 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197848', 'isradipine 2.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197849', 'isradipine 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197884', 'lisinopril 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197885', 'hydrochlorothiazide 12.5 MG / lisinopril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197886', 'hydrochlorothiazide 12.5 MG / lisinopril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197887', 'hydrochlorothiazide 25 MG / lisinopril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197951', 'methyclothiazide 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197956', 'methyldopa 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197958', 'methyldopa 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197960', 'hydrochlorothiazide 25 MG / methyldopa 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197963', 'hydrochlorothiazide 15 MG / methyldopa 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197978', 'metolazone 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197979', 'metolazone 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197986', 'minoxidil 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197987', 'minoxidil 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198000', 'bendroflumethiazide 5 MG / nadolol 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198001', 'bendroflumethiazide 5 MG / nadolol 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198006', 'nadolol 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198007', 'nadolol 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198008', 'nadolol 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198032', 'nifedipine 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198033', 'nifedipine 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198034', '24 HR nifedipine 30 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198035', '24 HR nifedipine 60 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198036', '24 HR nifedipine 90 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198104', 'pindolol 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198105', 'pindolol 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198141', 'prazosin 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198188', 'ramipril 2.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198189', 'ramipril 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198222', 'spironolactone 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198223', 'spironolactone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198224', 'hydrochlorothiazide 25 MG / spironolactone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198225', 'hydrochlorothiazide 50 MG / spironolactone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198284', 'timolol 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198285', 'timolol 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198286', 'timolol 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198312', 'triamterene 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198313', 'triamterene 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198314', 'hydrochlorothiazide 25 MG / triamterene 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198316', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198369', 'torsemide 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198370', 'torsemide 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198371', 'torsemide 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198372', 'torsemide 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199351', 'trandolapril 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199352', 'trandolapril 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199353', 'trandolapril 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1996254', 'valsartan 4 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199903', 'hydrochlorothiazide 12.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999031', '24 HR metoprolol succinate 100 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999033', '24 HR metoprolol succinate 200 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999035', '24 HR metoprolol succinate 25 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999037', '24 HR metoprolol succinate 50 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200031', 'carvedilol 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200032', 'carvedilol 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200033', 'carvedilol 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200094', 'irbesartan 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200095', 'irbesartan 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200096', 'irbesartan 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200284', 'hydrochlorothiazide 12.5 MG / valsartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200285', 'hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2047715', 'amlodipine 2.5 MG / celecoxib 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2047716', 'amlodipine 5 MG / celecoxib 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2047717', 'amlodipine 10 MG / celecoxib 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205304', 'telmisartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205305', 'telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205326', 'lisinopril 30 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2184120', 'amlodipine 1 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2477889', '4 ML labetalol hydrochloride 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2479564', '200 ML labetalol hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2479566', '100 ML labetalol hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2479567', '300 ML labetalol hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '251856', 'ramipril 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '251857', 'ramipril 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2586034', '125 ML diltiazem hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2586036', '250 ML diltiazem hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589881', 'torsemide 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589885', 'torsemide 60 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2598343', '2 ML labetalol hydrochloride 5 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2599173', 'amlodipine 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260376', 'terazosin 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261962', 'ramipril 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2621022', '10 ML furosemide 8 MG/ML Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '282486', 'bumetanide 0.25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '282755', 'telmisartan 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283316', 'hydrochlorothiazide 12.5 MG / telmisartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283317', 'hydrochlorothiazide 12.5 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308135', 'amlodipine 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308136', 'amlodipine 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308962', 'captopril 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308963', 'captopril 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308964', 'captopril 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309198', 'chlorothiazide 50 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310140', 'eprosartan 600 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310429', 'furosemide 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310792', 'hydrochlorothiazide 12.5 MG / irbesartan 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310793', 'hydrochlorothiazide 12.5 MG / irbesartan 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310796', 'hydrochlorothiazide 12.5 MG / quinapril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310797', 'hydrochlorothiazide 12.5 MG / quinapril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310798', 'hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310809', 'hydrochlorothiazide 25 MG / quinapril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310812', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310818', 'hydrochlorothiazide 50 MG / triamterene 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311353', 'lisinopril 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311354', 'lisinopril 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311671', 'metolazone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311984', '24 HR nisoldipine 20 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311985', '24 HR nisoldipine 30 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312593', 'prazosin 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312594', 'prazosin 2 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312748', 'quinapril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312749', 'quinapril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312750', 'quinapril 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313096', 'spironolactone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313215', 'terazosin 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313217', 'terazosin 2 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313219', 'terazosin 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313988', 'furosemide 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314076', 'lisinopril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314077', 'lisinopril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314203', 'quinapril 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317173', 'captopril 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349199', 'valsartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349200', 'valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349201', 'valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349353', 'hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349373', 'olmesartan medoxomil 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349401', 'olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349405', 'olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349483', 'valsartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351256', 'eplerenone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351257', 'eplerenone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351292', 'eprosartan 600 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351293', 'eprosartan 600 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360344', '24 HR nisoldipine 40 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '387013', 'nebivolol 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '401965', 'ramipril 1.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '401968', 'ramipril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402695', '24 HR felodipine 10 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402696', '24 HR felodipine 5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402698', '24 HR felodipine 2.5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403853', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403854', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403855', 'hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404011', 'amlodipine 5 MG / atorvastatin 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404013', 'amlodipine 10 MG / atorvastatin 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '429503', 'hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '477130', 'hydrochlorothiazide 25 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '484152', 'chlorothiazide 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '485471', 'hydrochlorothiazide 25 MG / irbesartan 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562518', '24 HR isradipine 10 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562520', '24 HR isradipine 5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '577776', 'candesartan cilexetil 16 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '578325', 'candesartan cilexetil 16 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '578330', 'candesartan cilexetil 32 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597967', 'amlodipine 10 MG / atorvastatin 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597971', 'amlodipine 2.5 MG / atorvastatin 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597974', 'amlodipine 2.5 MG / atorvastatin 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597977', 'amlodipine 5 MG / atorvastatin 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597980', 'amlodipine 5 MG / atorvastatin 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597984', 'amlodipine 5 MG / atorvastatin 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597987', 'amlodipine 10 MG / atorvastatin 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597990', 'amlodipine 10 MG / atorvastatin 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597993', 'amlodipine 2.5 MG / atorvastatin 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636042', 'hydrochlorothiazide 12.5 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636045', 'hydrochlorothiazide 25 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636360', '24 HR doxazosin 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636361', '24 HR doxazosin 8 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '639537', 'candesartan cilexetil 32 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '686924', 'carvedilol 3.125 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '722126', 'amlodipine 10 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '722131', 'amlodipine 10 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '722134', 'amlodipine 5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '722137', 'amlodipine 5 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727574', '10 ML furosemide 10 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727575', '4 ML furosemide 10 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '730861', 'amlodipine 10 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '730866', 'amlodipine 10 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '730869', 'amlodipine 5 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '730872', 'amlodipine 5 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '751612', 'nebivolol 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '751618', 'nebivolol 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763519', '24 HR nisoldipine 17 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763574', '24 HR nisoldipine 25.5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763589', '24 HR nisoldipine 34 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '790489', '24 HR nisoldipine 8.5 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '802749', 'candesartan cilexetil 32 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '827073', 'nebivolol 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830795', '24 HR diltiazem hydrochloride 360 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830801', '24 HR diltiazem hydrochloride 300 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830837', '24 HR diltiazem hydrochloride 240 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830845', '24 HR diltiazem hydrochloride 180 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830861', '24 HR diltiazem hydrochloride 120 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830865', '12 HR diltiazem hydrochloride 60 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830869', '12 HR diltiazem hydrochloride 90 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830872', '12 HR diltiazem hydrochloride 120 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830874', '24 HR diltiazem hydrochloride 120 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830877', '24 HR diltiazem hydrochloride 180 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830879', '24 HR diltiazem hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830882', '24 HR diltiazem hydrochloride 300 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830897', '24 HR diltiazem hydrochloride 360 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '830900', '24 HR diltiazem hydrochloride 420 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '831054', 'diltiazem hydrochloride 120 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '831102', 'diltiazem hydrochloride 90 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '831103', 'diltiazem hydrochloride 60 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '831359', '24 HR diltiazem hydrochloride 420 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '833217', 'diltiazem hydrochloride 30 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845488', 'ramipril 1.25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848131', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848135', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848140', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848145', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848151', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854901', 'bisoprolol fumarate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854905', 'bisoprolol fumarate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854908', 'bisoprolol fumarate 10 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854916', 'bisoprolol fumarate 2.5 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854919', 'bisoprolol fumarate 5 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854925', 'perindopril erbumine 8 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854984', 'perindopril erbumine 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854988', 'perindopril erbumine 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856422', 'hydrochlorothiazide 25 MG / propranolol hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856429', 'hydrochlorothiazide 25 MG / propranolol hydrochloride 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856443', '1 ML propranolol hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856448', 'propranolol hydrochloride 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856457', 'propranolol hydrochloride 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856460', '24 HR propranolol hydrochloride 120 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856481', '24 HR propranolol hydrochloride 160 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856519', 'propranolol hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856535', '24 HR propranolol hydrochloride 60 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856556', 'propranolol hydrochloride 60 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856569', '24 HR propranolol hydrochloride 80 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856578', 'propranolol hydrochloride 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856724', 'propranolol hydrochloride 4 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856733', 'propranolol hydrochloride 8 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857166', 'fosinopril sodium 10 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857169', 'fosinopril sodium 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857174', 'fosinopril sodium 20 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857183', 'fosinopril sodium 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857187', 'fosinopril sodium 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858580', '12 HR nicardipine hydrochloride 45 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858587', '12 HR nicardipine hydrochloride 30 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858599', '200 ML nicardipine hydrochloride 0.1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858603', '200 ML nicardipine hydrochloride 0.2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858607', '10 ML nicardipine hydrochloride 2.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858613', 'nicardipine hydrochloride 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858616', 'nicardipine hydrochloride 30 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858804', 'enalapril maleate 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858810', 'enalapril maleate 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858813', 'enalapril maleate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858817', 'enalapril maleate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858824', 'enalapril maleate 5 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858828', 'enalapril maleate 10 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860510', '24 HR carvedilol phosphate 10 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860516', '24 HR carvedilol phosphate 20 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860522', '24 HR carvedilol phosphate 40 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860532', '24 HR carvedilol phosphate 80 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '862006', '24 HR guanfacine 1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '862013', '24 HR guanfacine 2 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '862019', '24 HR guanfacine 3 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '862025', '24 HR guanfacine 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866412', '24 HR metoprolol succinate 100 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866419', '24 HR metoprolol succinate 200 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866427', '24 HR metoprolol succinate 25 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866436', '24 HR metoprolol succinate 50 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866452', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 100 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866461', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 25 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866472', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 50 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866479', 'hydrochlorothiazide 25 MG / metoprolol tartrate 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866482', 'hydrochlorothiazide 25 MG / metoprolol tartrate 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866491', 'hydrochlorothiazide 50 MG / metoprolol tartrate 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866508', '5 ML metoprolol tartrate 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866511', 'metoprolol tartrate 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866514', 'metoprolol tartrate 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866924', 'metoprolol tartrate 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '876514', 'amlodipine 10 MG / telmisartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '876519', 'amlodipine 10 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '876524', 'amlodipine 5 MG / telmisartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '876529', 'amlodipine 5 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884173', 'clonidine hydrochloride 0.1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884185', 'clonidine hydrochloride 0.2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884189', 'clonidine hydrochloride 0.3 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884192', 'chlorthalidone 15 MG / clonidine hydrochloride 0.1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884198', 'chlorthalidone 15 MG / clonidine hydrochloride 0.2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884203', 'chlorthalidone 15 MG / clonidine hydrochloride 0.3 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884221', '10 ML clonidine hydrochloride 0.1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884225', '10 ML clonidine hydrochloride 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '885880', '24 HR clonidine 0.17 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896758', 'labetalol hydrochloride 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896762', 'labetalol hydrochloride 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896766', 'labetalol hydrochloride 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '896771', 'labetalol hydrochloride 5 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897584', '24 HR verapamil hydrochloride 100 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897590', '24 HR verapamil hydrochloride 200 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897596', '24 HR verapamil hydrochloride 300 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897612', '24 HR verapamil hydrochloride 120 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897618', '24 HR verapamil hydrochloride 180 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897624', '24 HR verapamil hydrochloride 240 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897630', '24 HR verapamil hydrochloride 360 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897640', 'verapamil hydrochloride 180 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897649', 'verapamil hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897659', 'verapamil hydrochloride 120 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897666', 'verapamil hydrochloride 120 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897683', 'verapamil hydrochloride 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897722', 'verapamil hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897781', '24 HR trandolapril 1 MG / verapamil hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897783', '24 HR trandolapril 2 MG / verapamil hydrochloride 180 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897844', '24 HR trandolapril 2 MG / verapamil hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897853', '24 HR trandolapril 4 MG / verapamil hydrochloride 240 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898316', '4 ML verapamil hydrochloride 2.5 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898342', 'amlodipine 10 MG / benazepril hydrochloride 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898346', 'amlodipine 10 MG / benazepril hydrochloride 40 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898350', 'amlodipine 2.5 MG / benazepril hydrochloride 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898353', 'amlodipine 5 MG / benazepril hydrochloride 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898356', 'amlodipine 5 MG / benazepril hydrochloride 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898359', 'amlodipine 5 MG / benazepril hydrochloride 40 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898362', 'benazepril hydrochloride 10 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898367', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898372', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898378', 'benazepril hydrochloride 5 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898687', 'benazepril hydrochloride 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898690', 'benazepril hydrochloride 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898719', 'benazepril hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898723', 'benazepril hydrochloride 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905199', 'hydralazine hydrochloride 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905222', 'hydralazine hydrochloride 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905225', 'hydralazine hydrochloride 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905377', 'hydralazine hydrochloride 37.5 MG / isosorbide dinitrate 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905395', 'hydralazine hydrochloride 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '966571', '1 ML hydralazine hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977880', 'amiloride hydrochloride 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977883', 'amiloride hydrochloride 5 MG / hydrochlorothiazide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979464', 'hydrochlorothiazide 12.5 MG / losartan potassium 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979468', 'hydrochlorothiazide 12.5 MG / losartan potassium 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979471', 'hydrochlorothiazide 25 MG / losartan potassium 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979480', 'losartan potassium 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979485', 'losartan potassium 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979492', 'losartan potassium 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998671', '168 HR clonidine 0.00417 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998675', '168 HR clonidine 0.00833 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998679', '168 HR clonidine 0.0125 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998685', 'acebutolol 400 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998689', 'acebutolol 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999967', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999986', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999991', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999996', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet')
) AS t (system, code, display) ;

