create or replace view htn__define_dx_essential as select * from (values
('http://hl7.org/fhir/sid/icd-10-cm', 'I10', 'Essential (primary) hypertension')
,('http://snomed.info/sct', '10725009', 'Benign hypertension (disorder)')
,('http://snomed.info/sct', '1078301000112109', 'Multiple drug intolerant hypertension (disorder)')
,('http://snomed.info/sct', '1201005', 'Benign essential hypertension (disorder)')
,('http://snomed.info/sct', '18416000', 'Essential hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '19769006', 'High-renin essential hypertension (disorder)')
,('http://snomed.info/sct', '23717007', 'Benign essential hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '35303009', 'Benign essential hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '371125006', 'Labile essential hypertension (disorder)')
,('http://snomed.info/sct', '40511000119107', 'Postpartum pre-existing essential hypertension (disorder)')
,('http://snomed.info/sct', '429457004', 'Systolic essential hypertension (disorder)')
,('http://snomed.info/sct', '461301000124109', 'Resistant hypertensive disorder (disorder)')
,('http://snomed.info/sct', '46481004', 'Low-renin essential hypertension (disorder)')
,('http://snomed.info/sct', '48146000', 'Diastolic hypertension (disorder)')
,('http://snomed.info/sct', '56218007', 'Systolic hypertension (disorder)')
,('http://snomed.info/sct', '59621000', 'Essential hypertension (disorder)')
,('http://snomed.info/sct', '59720008', 'Sustained diastolic hypertension (disorder)')
,('http://snomed.info/sct', '63287004', 'Benign essential hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '65518004', 'Labile diastolic hypertension (disorder)')
,('http://snomed.info/sct', '71874008', 'Benign essential hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '72022006', 'Essential hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '762463000', 'Diastolic hypertension co-occurrent with systolic hypertension (disorder)')
,('http://snomed.info/sct', '78808002', 'Essential hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '78975002', 'Malignant essential hypertension (disorder)')
,('http://snomed.info/sct', '9901000', 'Essential hypertension complicating AND/OR reason for care during puerperium (disorder)')
) AS t (system, code, display) ;