create or replace view htn__define_frailty as select * from (values
('http://snomed.info/sct', '183240000', 'Self-propelled wheelchair (physical object)')
,('http://snomed.info/sct', '183241001', 'Pedal powered wheelchair (physical object)')
,('http://snomed.info/sct', '183248007', 'Attendant powered wheelchair (physical object)')
,('http://snomed.info/sct', '228869008', 'Manual wheelchair (physical object)')
,('http://snomed.info/sct', '23366006', 'Motorized wheelchair device (physical object)')
,('http://snomed.info/sct', '23562009', 'Household ventilator, device (physical object)')
,('http://snomed.info/sct', '261323006', 'Portable oxygen cylinder (physical object)')
,('http://snomed.info/sct', '262177002', 'Static oxygen cylinder (physical object)')
,('http://snomed.info/sct', '360006004', 'Walking stick (physical object)')
,('http://snomed.info/sct', '360008003', 'Commode (physical object)')
,('http://snomed.info/sct', '360299009', 'Long cane (physical object)')
,('http://snomed.info/sct', '371786002', 'Pressure support ventilator (physical object)')
,('http://snomed.info/sct', '37874008', 'Continuing positive airway pressure unit, device (physical object)')
,('http://snomed.info/sct', '391685000', 'Oxygen gas cylinder DD (physical object)')
,('http://snomed.info/sct', '391686004', 'Oxygen gas cylinder HD (physical object)')
,('http://snomed.info/sct', '391687008', 'Oxygen gas cylinder RD (physical object)')
,('http://snomed.info/sct', '391688003', 'Oxygen gas cylinder DF (physical object)')
,('http://snomed.info/sct', '391689006', 'Oxygen gas cylinder HX (physical object)')
,('http://snomed.info/sct', '391880008', 'Oxygen gas cylinder F (physical object)')
,('http://snomed.info/sct', '391881007', 'Oxygen gas cylinder AF (physical object)')
,('http://snomed.info/sct', '401953003', 'Oxygen composite cylinder with integral headset 1360 liters (physical object)')
,('http://snomed.info/sct', '401954009', 'Oxygen cylinder 1360 liters (physical object)')
,('http://snomed.info/sct', '401955005', 'Oxygen cylinder 300 liters (physical object)')
,('http://snomed.info/sct', '426160001', 'Oxygen ventilator (physical object)')
,('http://snomed.info/sct', '462987000', 'Patient/medical device walker (physical object)')
,('http://snomed.info/sct', '463093001', 'Patient/medical device walker, home-use (physical object)')
,('http://snomed.info/sct', '464002006', 'Portable ventilator, electric (physical object)')
,('http://snomed.info/sct', '464157006', 'Multiple-base walking stick (physical object)')
,('http://snomed.info/sct', '464405003', 'Multi-terrain sports wheelchair, attendant/occupant-driven (physical object)')
,('http://snomed.info/sct', '464443000', 'Stand-up wheelchair (physical object)')
,('http://snomed.info/sct', '464571009', 'Multi-terrain sports wheelchair, electric-motor-driven (physical object)')
,('http://snomed.info/sct', '464752005', 'Multi-terrain sports wheelchair, occupant-driven (physical object)')
,('http://snomed.info/sct', '465159000', 'Stair-climbing wheelchair (physical object)')
,('http://snomed.info/sct', '465556004', 'Single-base walking stick (physical object)')
,('http://snomed.info/sct', '465565006', 'Transport wheelchair, collapsible (physical object)')
,('http://snomed.info/sct', '465921009', 'Ventilation rocking bed (physical object)')
,('http://snomed.info/sct', '466182009', 'Wheelchair, occupant-driven, front-wheels-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466193006', 'Wheelchair, power-assisted, occupant-controlled, non-collapsible (physical object)')
,('http://snomed.info/sct', '466213002', 'Wheelchair, electric-motor-driven, occupant-controlled, manual-steering, collapsible (physical object)')
,('http://snomed.info/sct', '466229005', 'Wheelchair, occupant-driven, bimanual-lever-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466284002', 'Wheelchair, attendant/occupant-driven, bimanual-lever-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466316007', 'Wheelchair, combustion-engine-driven, non-collapsible (physical object)')
,('http://snomed.info/sct', '466317003', 'Basic walker, foldable (physical object)')
,('http://snomed.info/sct', '466322003', 'Wheelchair, power-assisted, attendant/occupant-controlled, non-collapsible (physical object)')
,('http://snomed.info/sct', '466331003', 'Wheelchair, attendant/occupant-driven, single-rear-wheel-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466337004', 'Wheelchair, attendant/occupant-driven, foot-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466340004', 'Wheelchair, occupant-driven, bimanual-lever-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466344008', 'Wheelchair, electric-motor-driven, occupant-controlled, powered-steering, non-collapsible (physical object)')
,('http://snomed.info/sct', '466351004', 'Walking chair, foldable (physical object)')
,('http://snomed.info/sct', '466364003', 'Wheelchair, attendant/occupant-driven, rear-wheels-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466365002', 'Wheelchair, electric-motor-driven, attendant/occupant-controlled, manual-steering, collapsible (physical object)')
,('http://snomed.info/sct', '466366001', 'Wheelchair, attendant/occupant-driven, single-lever-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466378002', 'Wheelchair, electric-motor-driven, occupant-controlled, powered-steering, collapsible (physical object)')
,('http://snomed.info/sct', '466381007', 'Wheelchair, attendant-driven, non-collapsible (physical object)')
,('http://snomed.info/sct', '466407009', 'Walking stick/seat (physical object)')
,('http://snomed.info/sct', '466464004', 'Basic walker, non-foldable (physical object)')
,('http://snomed.info/sct', '466466002', 'Wheelchair, occupant-driven, foot-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466473007', 'Wheelchair, electric-motor-driven, attendant-controlled, manual-steering, collapsible (physical object)')
,('http://snomed.info/sct', '466477008', 'Wheelchair, electric-motor-driven, occupant-controlled, manual-steering, non-collapsible (physical object)')
,('http://snomed.info/sct', '466486003', 'Wheelchair, attendant/occupant-driven, bimanual-lever-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466494005', 'Wheelchair, power-assisted, attendant-controlled, collapsible (physical object)')
,('http://snomed.info/sct', '466524001', 'Wheelchair, attendant-driven, collapsible (physical object)')
,('http://snomed.info/sct', '466533004', 'Wheelchair, attendant/occupant-driven, foot-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466538008', 'Room humidifier (physical object)')
,('http://snomed.info/sct', '466550002', 'Wheelchair, attendant/occupant-driven, rear-wheels-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466553000', 'Wheelchair, occupant-driven, single-lever-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466576002', 'Wheelchair, occupant-driven, bimanual-chain-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466607002', 'Wheelchair, attendant/occupant-driven, single-lever-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466616003', 'Wheelchair, attendant/occupant-driven, single-rear-wheel-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466619005', 'Wheelchair, attendant/occupant-driven, bimanual-chain-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466644002', 'Wheelchair, occupant-driven, bimanual-chain-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466671002', 'Wheelchair, combustion-engine-driven, collapsible (physical object)')
,('http://snomed.info/sct', '466695000', 'Wheelchair, attendant/occupant-driven, single-front-wheel-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466699006', 'Wheelchair, power-assisted, attendant/occupant-controlled, collapsible (physical object)')
,('http://snomed.info/sct', '466721007', 'Wheelchair, power-assisted, attendant-controlled, non-collapsible (physical object)')
,('http://snomed.info/sct', '466739003', 'Wheelchair, occupant-driven, front-wheels-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466758007', 'Wheelchair, electric-motor-driven, attendant-controlled, manual-steering, non-collapsible (physical object)')
,('http://snomed.info/sct', '466786004', 'Basic electric hospital bed (physical object)')
,('http://snomed.info/sct', '466809001', 'Wheelchair, attendant/occupant-driven, bimanual-chain-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466813008', 'Wheelchair, electric-motor-driven, attendant-controlled, powered-steering, non-collapsible (physical object)')
,('http://snomed.info/sct', '466851008', 'Wheelchair, attendant/occupant-driven, front-wheels-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466871004', 'Wheelchair, electric-motor-driven, attendant/occupant-controlled, powered-steering, non-collapsible (physical object)')
,('http://snomed.info/sct', '466889003', 'Wheelchair, attendant/occupant-driven, single-front-wheel-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466926008', 'Wheelchair, occupant-driven, rear-wheels-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466927004', 'Wheelchair, electric-motor-driven, attendant/occupant-controlled, powered-steering, collapsible (physical object)')
,('http://snomed.info/sct', '466938004', 'Wheelchair, occupant-driven, single-rear-wheel-operated, collapsible (physical object)')
,('http://snomed.info/sct', '466947007', 'Wheelchair, occupant-driven, rear-wheels-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466966007', 'Wheelchair, occupant-driven, foot-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466986006', 'Walking table (physical object)')
,('http://snomed.info/sct', '466989004', 'Wheelchair, attendant/occupant-driven, front-wheels-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '466999009', 'Wheelchair, electric-motor-driven, attendant-controlled, powered-steering, collapsible (physical object)')
,('http://snomed.info/sct', '467018005', 'Wheelchair, occupant-driven, single-lever-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '467065004', 'Wheelchair, occupant-driven, single-front-wheel-operated, collapsible (physical object)')
,('http://snomed.info/sct', '467077009', 'Wheelchair, electric-motor-driven, attendant/occupant-controlled, manual-steering, non-collapsible (physical object)')
,('http://snomed.info/sct', '467095007', 'Wheelchair, power-assisted, occupant-controlled, collapsible (physical object)')
,('http://snomed.info/sct', '467137003', 'Wheelchair, occupant-driven, single-rear-wheel-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '467155007', 'Walking chair, non-foldable (physical object)')
,('http://snomed.info/sct', '467163008', 'Wheelchair, occupant-driven, single-front-wheel-operated, non-collapsible (physical object)')
,('http://snomed.info/sct', '469361005', 'Heat/moisture exchanger, reusable (physical object)')
,('http://snomed.info/sct', '469860004', 'All-plastic conventional wheelchair (physical object)')
,('http://snomed.info/sct', '470119002', 'Heat/moisture exchanger, single-use (physical object)')
,('http://snomed.info/sct', '470174002', 'Heat/moisture exchanger insertable filter (physical object)')
,('http://snomed.info/sct', '58938008', 'Wheelchair device (physical object)')
,('http://snomed.info/sct', '66435007', 'Electric bed, device (physical object)')
,('http://snomed.info/sct', '700593005', 'Heated respiratory humidifier (physical object)')
,('http://snomed.info/sct', '700705005', 'Non-heated respiratory humidifier (physical object)')
,('http://snomed.info/sct', '700910000', 'Ultrasonic respiratory humidifier (physical object)')
,('http://snomed.info/sct', '702172008', 'Home continuous positive airway pressure unit (physical object)')
,('http://snomed.info/sct', '702173003', 'Home bilevel positive airway pressure unit (physical object)')
,('http://snomed.info/sct', '705404007', 'Walker/Walking frame (physical object)')
,('http://snomed.info/sct', '705406009', 'Walker (physical object)')
,('http://snomed.info/sct', '705419008', 'Special-function wheelchair (physical object)')
,('http://snomed.info/sct', '705421003', 'Sports wheelchair (physical object)')
,('http://snomed.info/sct', '705422005', 'Power-driven wheelchair (physical object)')
,('http://snomed.info/sct', '705423000', 'Electric-motor-driven wheelchair (physical object)')
,('http://snomed.info/sct', '705425007', 'Attendant/occupant-controlled electric-motor-driven wheelchair (physical object)')
,('http://snomed.info/sct', '705426008', 'Attendant-controlled electric-motor-driven wheelchair (physical object)')
,('http://snomed.info/sct', '705427004', 'Power-assisted wheelchair (physical object)')
,('http://snomed.info/sct', '705428009', 'Manual-driven wheelchair (physical object)')
,('http://snomed.info/sct', '706180003', 'Respiratory humidifier (physical object)')
,('http://snomed.info/sct', '714700001', 'Bilevel positive airway pressure unit hand held (physical object)')
,('http://snomed.info/sct', '71545009', 'Household humidifier, device (physical object)')
,('http://snomed.info/sct', '781471009', 'Gait rehabilitation electronic walker (physical object)')
,('http://snomed.info/sct', '87405001', 'Cane, device (physical object)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.000', 'Pressure ulcer of unspecified elbow, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.001', 'Pressure ulcer of unspecified elbow, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.002', 'Pressure ulcer of unspecified elbow, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.003', 'Pressure ulcer of unspecified elbow, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.004', 'Pressure ulcer of unspecified elbow, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.006', 'Pressure-induced deep tissue damage of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.009', 'Pressure ulcer of unspecified elbow, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.010', 'Pressure ulcer of right elbow, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.011', 'Pressure ulcer of right elbow, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.012', 'Pressure ulcer of right elbow, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.013', 'Pressure ulcer of right elbow, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.014', 'Pressure ulcer of right elbow, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.016', 'Pressure-induced deep tissue damage of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.019', 'Pressure ulcer of right elbow, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.020', 'Pressure ulcer of left elbow, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.021', 'Pressure ulcer of left elbow, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.022', 'Pressure ulcer of left elbow, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.023', 'Pressure ulcer of left elbow, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.024', 'Pressure ulcer of left elbow, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.026', 'Pressure-induced deep tissue damage of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.029', 'Pressure ulcer of left elbow, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.100', 'Pressure ulcer of unspecified part of back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.101', 'Pressure ulcer of unspecified part of back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.102', 'Pressure ulcer of unspecified part of back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.103', 'Pressure ulcer of unspecified part of back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.104', 'Pressure ulcer of unspecified part of back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.106', 'Pressure-induced deep tissue damage of unspecified part of back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.109', 'Pressure ulcer of unspecified part of back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.110', 'Pressure ulcer of right upper back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.111', 'Pressure ulcer of right upper back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.112', 'Pressure ulcer of right upper back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.113', 'Pressure ulcer of right upper back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.114', 'Pressure ulcer of right upper back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.116', 'Pressure-induced deep tissue damage of right upper back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.119', 'Pressure ulcer of right upper back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.120', 'Pressure ulcer of left upper back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.121', 'Pressure ulcer of left upper back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.122', 'Pressure ulcer of left upper back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.123', 'Pressure ulcer of left upper back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.124', 'Pressure ulcer of left upper back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.126', 'Pressure-induced deep tissue damage of left upper back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.129', 'Pressure ulcer of left upper back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.130', 'Pressure ulcer of right lower back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.131', 'Pressure ulcer of right lower back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.132', 'Pressure ulcer of right lower back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.133', 'Pressure ulcer of right lower back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.134', 'Pressure ulcer of right lower back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.136', 'Pressure-induced deep tissue damage of right lower back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.139', 'Pressure ulcer of right lower back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.140', 'Pressure ulcer of left lower back, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.141', 'Pressure ulcer of left lower back, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.142', 'Pressure ulcer of left lower back, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.143', 'Pressure ulcer of left lower back, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.144', 'Pressure ulcer of left lower back, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.146', 'Pressure-induced deep tissue damage of left lower back')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.149', 'Pressure ulcer of left lower back, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.150', 'Pressure ulcer of sacral region, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.151', 'Pressure ulcer of sacral region, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.152', 'Pressure ulcer of sacral region, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.153', 'Pressure ulcer of sacral region, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.154', 'Pressure ulcer of sacral region, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.156', 'Pressure-induced deep tissue damage of sacral region')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.159', 'Pressure ulcer of sacral region, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.200', 'Pressure ulcer of unspecified hip, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.201', 'Pressure ulcer of unspecified hip, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.202', 'Pressure ulcer of unspecified hip, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.203', 'Pressure ulcer of unspecified hip, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.204', 'Pressure ulcer of unspecified hip, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.206', 'Pressure-induced deep tissue damage of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.209', 'Pressure ulcer of unspecified hip, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.210', 'Pressure ulcer of right hip, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.211', 'Pressure ulcer of right hip, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.212', 'Pressure ulcer of right hip, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.213', 'Pressure ulcer of right hip, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.214', 'Pressure ulcer of right hip, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.216', 'Pressure-induced deep tissue damage of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.219', 'Pressure ulcer of right hip, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.220', 'Pressure ulcer of left hip, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.221', 'Pressure ulcer of left hip, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.222', 'Pressure ulcer of left hip, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.223', 'Pressure ulcer of left hip, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.224', 'Pressure ulcer of left hip, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.226', 'Pressure-induced deep tissue damage of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.229', 'Pressure ulcer of left hip, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.300', 'Pressure ulcer of unspecified buttock, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.301', 'Pressure ulcer of unspecified buttock, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.302', 'Pressure ulcer of unspecified buttock, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.303', 'Pressure ulcer of unspecified buttock, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.304', 'Pressure ulcer of unspecified buttock, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.306', 'Pressure-induced deep tissue damage of unspecified buttock')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.309', 'Pressure ulcer of unspecified buttock, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.310', 'Pressure ulcer of right buttock, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.311', 'Pressure ulcer of right buttock, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.312', 'Pressure ulcer of right buttock, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.313', 'Pressure ulcer of right buttock, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.314', 'Pressure ulcer of right buttock, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.316', 'Pressure-induced deep tissue damage of right buttock')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.319', 'Pressure ulcer of right buttock, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.320', 'Pressure ulcer of left buttock, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.321', 'Pressure ulcer of left buttock, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.322', 'Pressure ulcer of left buttock, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.323', 'Pressure ulcer of left buttock, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.324', 'Pressure ulcer of left buttock, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.326', 'Pressure-induced deep tissue damage of left buttock')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.329', 'Pressure ulcer of left buttock, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.40', 'Pressure ulcer of contiguous site of back, buttock and hip, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.41', 'Pressure ulcer of contiguous site of back, buttock and hip, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.42', 'Pressure ulcer of contiguous site of back, buttock and hip, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.43', 'Pressure ulcer of contiguous site of back, buttock and hip, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.44', 'Pressure ulcer of contiguous site of back, buttock and hip, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.45', 'Pressure ulcer of contiguous site of back, buttock and hip, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.46', 'Pressure-induced deep tissue damage of contiguous site of back, buttock and hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.500', 'Pressure ulcer of unspecified ankle, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.501', 'Pressure ulcer of unspecified ankle, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.502', 'Pressure ulcer of unspecified ankle, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.503', 'Pressure ulcer of unspecified ankle, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.504', 'Pressure ulcer of unspecified ankle, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.506', 'Pressure-induced deep tissue damage of unspecified ankle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.509', 'Pressure ulcer of unspecified ankle, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.510', 'Pressure ulcer of right ankle, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.511', 'Pressure ulcer of right ankle, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.512', 'Pressure ulcer of right ankle, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.513', 'Pressure ulcer of right ankle, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.514', 'Pressure ulcer of right ankle, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.516', 'Pressure-induced deep tissue damage of right ankle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.519', 'Pressure ulcer of right ankle, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.520', 'Pressure ulcer of left ankle, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.521', 'Pressure ulcer of left ankle, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.522', 'Pressure ulcer of left ankle, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.523', 'Pressure ulcer of left ankle, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.524', 'Pressure ulcer of left ankle, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.526', 'Pressure-induced deep tissue damage of left ankle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.529', 'Pressure ulcer of left ankle, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.600', 'Pressure ulcer of unspecified heel, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.601', 'Pressure ulcer of unspecified heel, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.602', 'Pressure ulcer of unspecified heel, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.603', 'Pressure ulcer of unspecified heel, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.604', 'Pressure ulcer of unspecified heel, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.606', 'Pressure-induced deep tissue damage of unspecified heel')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.609', 'Pressure ulcer of unspecified heel, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.610', 'Pressure ulcer of right heel, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.611', 'Pressure ulcer of right heel, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.612', 'Pressure ulcer of right heel, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.613', 'Pressure ulcer of right heel, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.614', 'Pressure ulcer of right heel, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.616', 'Pressure-induced deep tissue damage of right heel')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.619', 'Pressure ulcer of right heel, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.620', 'Pressure ulcer of left heel, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.621', 'Pressure ulcer of left heel, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.622', 'Pressure ulcer of left heel, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.623', 'Pressure ulcer of left heel, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.624', 'Pressure ulcer of left heel, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.626', 'Pressure-induced deep tissue damage of left heel')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.629', 'Pressure ulcer of left heel, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.810', 'Pressure ulcer of head, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.811', 'Pressure ulcer of head, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.812', 'Pressure ulcer of head, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.813', 'Pressure ulcer of head, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.814', 'Pressure ulcer of head, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.816', 'Pressure-induced deep tissue damage of head')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.819', 'Pressure ulcer of head, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.890', 'Pressure ulcer of other site, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.891', 'Pressure ulcer of other site, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.892', 'Pressure ulcer of other site, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.893', 'Pressure ulcer of other site, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.894', 'Pressure ulcer of other site, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.896', 'Pressure-induced deep tissue damage of other site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.899', 'Pressure ulcer of other site, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.90', 'Pressure ulcer of unspecified site, unspecified stage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.91', 'Pressure ulcer of unspecified site, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.92', 'Pressure ulcer of unspecified site, stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.93', 'Pressure ulcer of unspecified site, stage 3')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.94', 'Pressure ulcer of unspecified site, stage 4')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.95', 'Pressure ulcer of unspecified site, unstageable')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L89.96', 'Pressure-induced deep tissue damage of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M62.50', 'Muscle wasting and atrophy, not elsewhere classified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M62.81', 'Muscle weakness (generalized)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M62.84', 'Sarcopenia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.0XXA', 'Fall on same level from slipping, tripping and stumbling without subsequent striking against object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.0XXD', 'Fall on same level from slipping, tripping and stumbling without subsequent striking against object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.0XXS', 'Fall on same level from slipping, tripping and stumbling without subsequent striking against object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.10XA', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.10XD', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.10XS', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.110A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against sharp glass, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.110D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against sharp glass, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.110S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against sharp glass, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.111A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against power tool or machine, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.111D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against power tool or machine, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.111S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against power tool or machine, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.118A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other sharp object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.118D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other sharp object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.118S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other sharp object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.119A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified sharp object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.119D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified sharp object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.119S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against unspecified sharp object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.190A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against furniture, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.190D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against furniture, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.190S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against furniture, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.198A', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.198D', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W01.198S', 'Fall on same level from slipping, tripping and stumbling with subsequent striking against other object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W06.XXXA', 'Fall from bed, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W06.XXXD', 'Fall from bed, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W06.XXXS', 'Fall from bed, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W07.XXXA', 'Fall from chair, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W07.XXXD', 'Fall from chair, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W07.XXXS', 'Fall from chair, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W08.XXXA', 'Fall from other furniture, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W08.XXXD', 'Fall from other furniture, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W08.XXXS', 'Fall from other furniture, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.0XXA', 'Fall (on)(from) escalator, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.0XXD', 'Fall (on)(from) escalator, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.0XXS', 'Fall (on)(from) escalator, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.1XXA', 'Fall (on)(from) sidewalk curb, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.1XXD', 'Fall (on)(from) sidewalk curb, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.1XXS', 'Fall (on)(from) sidewalk curb, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.2XXA', 'Fall (on)(from) incline, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.2XXD', 'Fall (on)(from) incline, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.2XXS', 'Fall (on)(from) incline, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.8XXA', 'Fall (on) (from) other stairs and steps, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.8XXD', 'Fall (on) (from) other stairs and steps, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.8XXS', 'Fall (on) (from) other stairs and steps, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.9XXA', 'Fall (on) (from) unspecified stairs and steps, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.9XXD', 'Fall (on) (from) unspecified stairs and steps, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W10.9XXS', 'Fall (on) (from) unspecified stairs and steps, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.00XA', 'Striking against unspecified object with subsequent fall, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.00XD', 'Striking against unspecified object with subsequent fall, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.00XS', 'Striking against unspecified object with subsequent fall, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.02XA', 'Striking against glass with subsequent fall, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.02XD', 'Striking against glass with subsequent fall, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.02XS', 'Striking against glass with subsequent fall, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.09XA', 'Striking against other object with subsequent fall, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.09XD', 'Striking against other object with subsequent fall, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.09XS', 'Striking against other object with subsequent fall, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.11XA', 'Fall from or off toilet without subsequent striking against object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.11XD', 'Fall from or off toilet without subsequent striking against object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.11XS', 'Fall from or off toilet without subsequent striking against object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.12XA', 'Fall from or off toilet with subsequent striking against object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.12XD', 'Fall from or off toilet with subsequent striking against object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.12XS', 'Fall from or off toilet with subsequent striking against object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.2XXA', 'Fall in (into) shower or empty bathtub, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.2XXD', 'Fall in (into) shower or empty bathtub, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.2XXS', 'Fall in (into) shower or empty bathtub, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.30XA', 'Fall on same level, unspecified, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.30XD', 'Fall on same level, unspecified, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.30XS', 'Fall on same level, unspecified, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.31XA', 'Fall on same level due to stepping on an object, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.31XD', 'Fall on same level due to stepping on an object, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.31XS', 'Fall on same level due to stepping on an object, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.39XA', 'Other fall on same level, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.39XD', 'Other fall on same level, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W18.39XS', 'Other fall on same level, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W19.XXXA', 'Unspecified fall, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W19.XXXD', 'Unspecified fall, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'W19.XXXS', 'Unspecified fall, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Y92.199', 'Unspecified place in other specified residential institution as the place of occurrence of the external cause')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z59.3', 'Problems related to living in residential institution')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z73.6', 'Limitation of activities due to disability')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.01', 'Bed confinement status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.09', 'Other reduced mobility')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.1', 'Need for assistance with personal care')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.2', 'Need for assistance at home and no other household member able to render care')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.3', 'Need for continuous supervision')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.8', 'Other problems related to care provider dependency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z74.9', 'Problem related to care provider dependency, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z91.81', 'History of falling')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.11', 'Dependence on respirator [ventilator] status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.3', 'Dependence on wheelchair')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.81', 'Dependence on supplemental oxygen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.89', 'Dependence on other enabling machines and devices')
,('http://snomed.info/sct', '10637031000119106', 'Pressure ulcer of buttock stage 1 (disorder)')
,('http://snomed.info/sct', '10637071000119109', 'Pressure ulcer of buttock stage 2 (disorder)')
,('http://snomed.info/sct', '10637111000119102', 'Pressure ulcer of buttock stage 3 (disorder)')
,('http://snomed.info/sct', '10637151000119101', 'Pressure ulcer of buttock stage 4 (disorder)')
,('http://snomed.info/sct', '129588001', 'Adult failure to thrive syndrome (disorder)')
,('http://snomed.info/sct', '138371000119104', 'Paresis as late effect of poliomyelitis (disorder)')
,('http://snomed.info/sct', '162845004', 'On examination - failure to thrive (disorder)')
,('http://snomed.info/sct', '16728003', 'Inherited spastic paresis (disorder)')
,('http://snomed.info/sct', '17886000', 'Fall from wheelchair (event)')
,('http://snomed.info/sct', '20902002', 'Fall from bed (event)')
,('http://snomed.info/sct', '214436006', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting (event)')
,('http://snomed.info/sct', '214437002', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, driver of motor vehicle injured (event)')
,('http://snomed.info/sct', '214438007', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, passenger of motor vehicle injured (event)')
,('http://snomed.info/sct', '214439004', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, motor cyclist injured (event)')
,('http://snomed.info/sct', '214441003', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, occupant of tram injured (event)')
,('http://snomed.info/sct', '214442005', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, rider of animal or occupant of animal-drawn vehicle injured (event)')
,('http://snomed.info/sct', '214443000', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, pedal cyclist injured (event)')
,('http://snomed.info/sct', '214444006', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, pedestrian injured (event)')
,('http://snomed.info/sct', '217082002', 'Accidental fall (event)')
,('http://snomed.info/sct', '217083007', 'Fall on or from stairs or steps (event)')
,('http://snomed.info/sct', '217084001', 'Fall on or from escalator (event)')
,('http://snomed.info/sct', '217086004', 'Fall from escalator (event)')
,('http://snomed.info/sct', '217088003', 'Fall on or from stairs (event)')
,('http://snomed.info/sct', '217090002', 'Fall from stairs (event)')
,('http://snomed.info/sct', '217092005', 'Fall on or from steps (event)')
,('http://snomed.info/sct', '217093000', 'Fall on steps (event)')
,('http://snomed.info/sct', '217094006', 'Fall from steps (event)')
,('http://snomed.info/sct', '217142006', 'Fall from chair or bed (event)')
,('http://snomed.info/sct', '217154006', 'Fall on same level from slipping, tripping or stumbling (event)')
,('http://snomed.info/sct', '217155007', 'Fall on same level from slipping (event)')
,('http://snomed.info/sct', '217156008', 'Fall on same level from tripping (event)')
,('http://snomed.info/sct', '217157004', 'Fall on same level from stumbling (event)')
,('http://snomed.info/sct', '217158009', 'Fall on moving sidewalk (event)')
,('http://snomed.info/sct', '217173005', 'Fall from bump against object (event)')
,('http://snomed.info/sct', '225558004', 'Pressure ulcer of back (disorder)')
,('http://snomed.info/sct', '225562005', 'Pressure ulcer of sacral region (disorder)')
,('http://snomed.info/sct', '225563000', 'Pressure ulcer of buttock (disorder)')
,('http://snomed.info/sct', '242109009', 'Fall down stairs of motor bus while boarding or alighting (event)')
,('http://snomed.info/sct', '242389003', 'Fall due to wet surface (event)')
,('http://snomed.info/sct', '242390007', 'Fall due to polished surface (event)')
,('http://snomed.info/sct', '242391006', 'Fall due to discarded object (event)')
,('http://snomed.info/sct', '242392004', 'Fall in bath or shower (event)')
,('http://snomed.info/sct', '242395002', 'Fall due to trip on loose carpet (event)')
,('http://snomed.info/sct', '242396001', 'Fall due to uneven surface indoors (event)')
,('http://snomed.info/sct', '242413007', 'Fall from furniture (event)')
,('http://snomed.info/sct', '242414001', 'Fall from stool (event)')
,('http://snomed.info/sct', '242419006', 'Fall from toilet seat (event)')
,('http://snomed.info/sct', '269699007', 'Fall on same level from impact against object (event)')
,('http://snomed.info/sct', '274918000', 'Fall on same level due to nature of surface (event)')
,('http://snomed.info/sct', '33036003', 'Fall on same level (event)')
,('http://snomed.info/sct', '40104005', 'Fall in home (event)')
,('http://snomed.info/sct', '414188008', 'Fall down stairs (event)')
,('http://snomed.info/sct', '414189000', 'Fall down steps (event)')
,('http://snomed.info/sct', '414190009', 'Fall on stairs (event)')
,('http://snomed.info/sct', '427849003', 'Fall on hard surface (event)')
,('http://snomed.info/sct', '428484005', 'Organic failure to thrive (disorder)')
,('http://snomed.info/sct', '429621003', 'Fall on concrete (event)')
,('http://snomed.info/sct', '44188002', 'Fall in shower (event)')
,('http://snomed.info/sct', '459821000124104', 'McArdle sign (finding)')
,('http://snomed.info/sct', '52702003', 'Chronic fatigue syndrome (disorder)')
,('http://snomed.info/sct', '56307009', 'Fall from table (event)')
,('http://snomed.info/sct', '67223001', 'Fall on escalator (event)')
,('http://snomed.info/sct', '699214007', 'Pressure ulcer of hip (disorder)')
,('http://snomed.info/sct', '699215008', 'Pressure ulcer of lower back (disorder)')
,('http://snomed.info/sct', '699216009', 'Pressure ulcer of coccygeal region (disorder)')
,('http://snomed.info/sct', '699218005', 'Pressure ulcer of upper back (disorder)')
,('http://snomed.info/sct', '715504003', 'Spastic paraparesis co-occurrent with deafness (disorder)')
,('http://snomed.info/sct', '74541001', 'Fall from bench (event)')
,('http://snomed.info/sct', '763829004', 'Oculopharyngodistal myopathy (disorder)')
,('http://snomed.info/sct', '823018004', 'Muscle paresis due to and following neuromuscular blockade (disorder)')
,('http://snomed.info/sct', '83468000', 'Fall from chair (event)')
,('http://snomed.info/sct', '8960001000004106', 'Pressure ulcer of skin of right ischial tuberosity region (disorder)')
,('http://snomed.info/sct', '90619006', 'Fall in bathtub (event)')
,('http://snomed.info/sct', '92341000119107', 'Weakness of extremities as sequela of stroke (disorder)')
,('http://snomed.info/sct', '10637031000119106', 'Pressure ulcer of buttock stage 1 (disorder)')
,('http://snomed.info/sct', '10637071000119109', 'Pressure ulcer of buttock stage 2 (disorder)')
,('http://snomed.info/sct', '10637111000119102', 'Pressure ulcer of buttock stage 3 (disorder)')
,('http://snomed.info/sct', '10637151000119101', 'Pressure ulcer of buttock stage 4 (disorder)')
,('http://snomed.info/sct', '129588001', 'Adult failure to thrive syndrome (disorder)')
,('http://snomed.info/sct', '138371000119104', 'Paresis as late effect of poliomyelitis (disorder)')
,('http://snomed.info/sct', '162845004', 'On examination - failure to thrive (disorder)')
,('http://snomed.info/sct', '16728003', 'Inherited spastic paresis (disorder)')
,('http://snomed.info/sct', '17886000', 'Fall from wheelchair (event)')
,('http://snomed.info/sct', '20902002', 'Fall from bed (event)')
,('http://snomed.info/sct', '214436006', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting (event)')
,('http://snomed.info/sct', '214437002', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, driver of motor vehicle injured (event)')
,('http://snomed.info/sct', '214438007', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, passenger of motor vehicle injured (event)')
,('http://snomed.info/sct', '214439004', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, motor cyclist injured (event)')
,('http://snomed.info/sct', '214441003', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, occupant of tram injured (event)')
,('http://snomed.info/sct', '214442005', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, rider of animal or occupant of animal-drawn vehicle injured (event)')
,('http://snomed.info/sct', '214443000', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, pedal cyclist injured (event)')
,('http://snomed.info/sct', '214444006', 'Noncollision motor vehicle traffic accident involving fall down stairs of motor bus while boarding or alighting, pedestrian injured (event)')
,('http://snomed.info/sct', '217082002', 'Accidental fall (event)')
,('http://snomed.info/sct', '217083007', 'Fall on or from stairs or steps (event)')
,('http://snomed.info/sct', '217084001', 'Fall on or from escalator (event)')
,('http://snomed.info/sct', '217086004', 'Fall from escalator (event)')
,('http://snomed.info/sct', '217088003', 'Fall on or from stairs (event)')
,('http://snomed.info/sct', '217090002', 'Fall from stairs (event)')
,('http://snomed.info/sct', '217092005', 'Fall on or from steps (event)')
,('http://snomed.info/sct', '217093000', 'Fall on steps (event)')
,('http://snomed.info/sct', '217094006', 'Fall from steps (event)')
,('http://snomed.info/sct', '217142006', 'Fall from chair or bed (event)')
,('http://snomed.info/sct', '217154006', 'Fall on same level from slipping, tripping or stumbling (event)')
,('http://snomed.info/sct', '217155007', 'Fall on same level from slipping (event)')
,('http://snomed.info/sct', '217156008', 'Fall on same level from tripping (event)')
,('http://snomed.info/sct', '217157004', 'Fall on same level from stumbling (event)')
,('http://snomed.info/sct', '217158009', 'Fall on moving sidewalk (event)')
,('http://snomed.info/sct', '217173005', 'Fall from bump against object (event)')
,('http://snomed.info/sct', '225558004', 'Pressure ulcer of back (disorder)')
,('http://snomed.info/sct', '225562005', 'Pressure ulcer of sacral region (disorder)')
,('http://snomed.info/sct', '225563000', 'Pressure ulcer of buttock (disorder)')
,('http://snomed.info/sct', '242109009', 'Fall down stairs of motor bus while boarding or alighting (event)')
,('http://snomed.info/sct', '242389003', 'Fall due to wet surface (event)')
,('http://snomed.info/sct', '242390007', 'Fall due to polished surface (event)')
,('http://snomed.info/sct', '242391006', 'Fall due to discarded object (event)')
,('http://snomed.info/sct', '242392004', 'Fall in bath or shower (event)')
,('http://snomed.info/sct', '242395002', 'Fall due to trip on loose carpet (event)')
,('http://snomed.info/sct', '242396001', 'Fall due to uneven surface indoors (event)')
,('http://snomed.info/sct', '242413007', 'Fall from furniture (event)')
,('http://snomed.info/sct', '242414001', 'Fall from stool (event)')
,('http://snomed.info/sct', '242419006', 'Fall from toilet seat (event)')
,('http://snomed.info/sct', '269699007', 'Fall on same level from impact against object (event)')
,('http://snomed.info/sct', '274918000', 'Fall on same level due to nature of surface (event)')
,('http://snomed.info/sct', '33036003', 'Fall on same level (event)')
,('http://snomed.info/sct', '40104005', 'Fall in home (event)')
,('http://snomed.info/sct', '414188008', 'Fall down stairs (event)')
,('http://snomed.info/sct', '414189000', 'Fall down steps (event)')
,('http://snomed.info/sct', '414190009', 'Fall on stairs (event)')
,('http://snomed.info/sct', '427849003', 'Fall on hard surface (event)')
,('http://snomed.info/sct', '428484005', 'Organic failure to thrive (disorder)')
,('http://snomed.info/sct', '429621003', 'Fall on concrete (event)')
,('http://snomed.info/sct', '44188002', 'Fall in shower (event)')
,('http://snomed.info/sct', '459821000124104', 'McArdle sign (finding)')
,('http://snomed.info/sct', '52702003', 'Chronic fatigue syndrome (disorder)')
,('http://snomed.info/sct', '56307009', 'Fall from table (event)')
,('http://snomed.info/sct', '67223001', 'Fall on escalator (event)')
,('http://snomed.info/sct', '699214007', 'Pressure ulcer of hip (disorder)')
,('http://snomed.info/sct', '699215008', 'Pressure ulcer of lower back (disorder)')
,('http://snomed.info/sct', '699216009', 'Pressure ulcer of coccygeal region (disorder)')
,('http://snomed.info/sct', '699218005', 'Pressure ulcer of upper back (disorder)')
,('http://snomed.info/sct', '715504003', 'Spastic paraparesis co-occurrent with deafness (disorder)')
,('http://snomed.info/sct', '74541001', 'Fall from bench (event)')
,('http://snomed.info/sct', '763829004', 'Oculopharyngodistal myopathy (disorder)')
,('http://snomed.info/sct', '823018004', 'Muscle paresis due to and following neuromuscular blockade (disorder)')
,('http://snomed.info/sct', '83468000', 'Fall from chair (event)')
,('http://snomed.info/sct', '8960001000004106', 'Pressure ulcer of skin of right ischial tuberosity region (disorder)')
,('http://snomed.info/sct', '90619006', 'Fall in bathtub (event)')
,('http://snomed.info/sct', '92341000119107', 'Weakness of extremities as sequela of stroke (disorder)')
,('http://www.ama-assn.org/go/cpt', '99504', 'Home visit for mechanical ventilation care')
,('http://www.ama-assn.org/go/cpt', '99509', 'Home visit for assistance with activities of daily living and personal care')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0162', 'Skilled services by a registered nurse (rn) for management and evaluation of the plan of care. each 15 minutes (the patients underlying condition or complication requires an rn to ensure that essential non-skilled care achieves its purpose in the home health or hospice setting)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0299', 'Direct skilled nursing services of a registered nurse (rn) in the home health or hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0300', 'Direct skilled nursing services of a licensed practical nurse (lpn) in the home health or hospice setting, each 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0493', 'Skilled services of a registered nurse (rn) for the observation and assessment of the patients condition, each 15 minutes (the change in the patients condition requires skilled nursing personnel to identify and evaluate the patients need for possible modification of treatment in the home health or hospice setting)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0494', 'Skilled services of a licensed practical nurse (lpn) for the observation and assessment of the patients condition, each 15 minutes (the change in the patients condition requires skilled nursing personnel to identify and evaluate the patients need for possible modification of treatment in the home health or hospice setting)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S0271', 'Physician management of patient home care, hospice monthly case rate (per 30 days)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S0311', 'Comprehensive management and care coordination for advanced illness, per calendar month')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S9123', 'Nursing care, in the home. by registered nurse, per hour (use for general nursing care only, not to be used when cpt codes 99500-99602 can be used)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S9124', 'Nursing care, in the home. by licensed practical nurse, per hour')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1000', 'Private duty / independent nursing service(s) - licensed, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1001', 'Nursing assessment / evaluation')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1002', 'Rn services, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1003', 'Lpn/lvn services, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1004', 'Services of a qualified nursing aide, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1005', 'Respite care services, up to 15 minutes')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1019', 'Personal care services, per 15 minutes, not for an inpatient or resident of a hospital, nursing facility, icf/mr or imd, part of the individualized plan of treatment (code may not be used to identify services provided by home health aide or certified nurse assistant)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1020', 'Personal care services, per diem, not for an inpatient or resident of a hospital, nursing facility, icf/mr or imd, part of the individualized plan of treatment (code may not be used to identify services provided by home health aide or certified nurse assistant)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1021', 'Home health aide or certified nurse assistant, per visit')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1022', 'Contracted home health agency services, all services provided under contract, per day')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1030', 'Nursing care, in the home, by registered nurse, per diem')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'T1031', 'Nursing care, in the home, by licensed practical nurse, per diem')
,('http://snomed.info/sct', '102492002', 'Failure to maintain weight (finding)')
,('http://snomed.info/sct', '102568007', 'Paresis of lower extremity (finding)')
,('http://snomed.info/sct', '105501005', 'Dependence on enabling machine or device (finding)')
,('http://snomed.info/sct', '105503008', 'Dependence on wheelchair (finding)')
,('http://snomed.info/sct', '105504002', 'Dependence on walking stick (finding)')
,('http://snomed.info/sct', '126013009', 'Subjective muscle weakness (finding)')
,('http://snomed.info/sct', '127378008', 'Bilateral paresis (finding)')
,('http://snomed.info/sct', '13791008', 'Asthenia (finding)')
,('http://snomed.info/sct', '152921000119101', 'Dependence on respiratory device (finding)')
,('http://snomed.info/sct', '15634971000119107', 'Weakness of bilateral upper limbs (finding)')
,('http://snomed.info/sct', '16018391000119104', 'Paresis of left lower limb (finding)')
,('http://snomed.info/sct', '16018431000119109', 'Paresis of right lower limb (finding)')
,('http://snomed.info/sct', '160681005', 'Mobile outside with aid (finding)')
,('http://snomed.info/sct', '160683008', 'Needs walking aid in home (finding)')
,('http://snomed.info/sct', '160684002', 'Confined to chair (finding)')
,('http://snomed.info/sct', '160685001', 'Bed-ridden (finding)')
,('http://snomed.info/sct', '160692006', 'Mobility very poor (finding)')
,('http://snomed.info/sct', '160693001', 'Mobility poor (finding)')
,('http://snomed.info/sct', '160734000', 'Lives in a nursing home (finding)')
,('http://snomed.info/sct', '160737007', 'Lives in an old peoples home (finding)')
,('http://snomed.info/sct', '161832001', 'Weight decreasing (finding)')
,('http://snomed.info/sct', '161873000', 'Heavy legs (finding)')
,('http://snomed.info/sct', '161874006', 'Heavy feeling (finding)')
,('http://snomed.info/sct', '162236007', 'Weakness present (finding)')
,('http://snomed.info/sct', '162239000', 'Abdominal weakness (finding)')
,('http://snomed.info/sct', '163600007', 'On examination - paresis (weakness) (finding)')
,('http://snomed.info/sct', '163695007', 'On examination - muscle power reduced (finding)')
,('http://snomed.info/sct', '16419651000119103', 'Dependence on biphasic positive airway pressure ventilation due to central sleep apnea syndrome (finding)')
,('http://snomed.info/sct', '165243005', 'Independent in wheelchair (finding)')
,('http://snomed.info/sct', '165244004', 'Minimal help in wheelchair (finding)')
,('http://snomed.info/sct', '18726006', 'Senile asthenia (finding)')
,('http://snomed.info/sct', '20940004', 'Spinal hemiparesis (finding)')
,('http://snomed.info/sct', '22090007', 'Scissoring gait (finding)')
,('http://snomed.info/sct', '22325002', 'Abnormal gait (finding)')
,('http://snomed.info/sct', '224960004', 'Tired (finding)')
,('http://snomed.info/sct', '225612007', 'Wheelchair bound (finding)')
,('http://snomed.info/sct', '22631008', 'Unsteady when walking (finding)')
,('http://snomed.info/sct', '23042008', 'Spinal paraparesis (finding)')
,('http://snomed.info/sct', '238108007', 'Cachexia (finding)')
,('http://snomed.info/sct', '248269005', 'Tired on least exertion (finding)')
,('http://snomed.info/sct', '248278004', 'Attacks of weakness (finding)')
,('http://snomed.info/sct', '248279007', 'Frailty (finding)')
,('http://snomed.info/sct', '249888000', 'Weakness of sternomastoid (finding)')
,('http://snomed.info/sct', '249937002', 'Truncal muscle weakness (finding)')
,('http://snomed.info/sct', '249938007', 'Weakness of back (finding)')
,('http://snomed.info/sct', '249939004', 'Proximal muscle weakness (finding)')
,('http://snomed.info/sct', '249940002', 'Shoulder girdle weakness (finding)')
,('http://snomed.info/sct', '249941003', 'Pelvic girdle weakness (finding)')
,('http://snomed.info/sct', '249942005', 'Distal muscle weakness (finding)')
,('http://snomed.info/sct', '249943000', 'Weakness of distal arms and legs (finding)')
,('http://snomed.info/sct', '249946008', 'Pyramidal type muscle weakness (finding)')
,('http://snomed.info/sct', '250003005', 'Low level sensorimotor gait disorder (finding)')
,('http://snomed.info/sct', '250015009', 'Arthritic gait (finding)')
,('http://snomed.info/sct', '250034009', 'Middle level sensorimotor gait disorder (finding)')
,('http://snomed.info/sct', '250038007', 'Retropulsion when walking (finding)')
,('http://snomed.info/sct', '250043000', 'High level sensorimotor gait disorder (finding)')
,('http://snomed.info/sct', '250044006', 'Cautious gait (finding)')
,('http://snomed.info/sct', '250045007', 'Tottering gait (finding)')
,('http://snomed.info/sct', '250052009', 'Petrens gait (finding)')
,('http://snomed.info/sct', '250054005', 'Frontal gait disorder (finding)')
,('http://snomed.info/sct', '250991000119100', 'Stumbling gait (finding)')
,('http://snomed.info/sct', '262285001', 'Weight decreased (finding)')
,('http://snomed.info/sct', '26544005', 'Muscle weakness (finding)')
,('http://snomed.info/sct', '267024001', 'Abnormal weight loss (finding)')
,('http://snomed.info/sct', '267031002', 'Tiredness symptom (finding)')
,('http://snomed.info/sct', '267032009', 'Tired all the time (finding)')
,('http://snomed.info/sct', '268964003', 'On examination - festination-Parkinson gait (finding)')
,('http://snomed.info/sct', '271795006', 'Malaise and fatigue (finding)')
,('http://snomed.info/sct', '271875007', 'Senile debility (finding)')
,('http://snomed.info/sct', '272036004', 'Complaining of debility and malaise (finding)')
,('http://snomed.info/sct', '272062008', 'Complaining of "tired all the time" (finding)')
,('http://snomed.info/sct', '275313006', 'Dragging leg (finding)')
,('http://snomed.info/sct', '284529003', 'Cardiac cachexia (finding)')
,('http://snomed.info/sct', '298283006', 'Hand muscle weakness (finding)')
,('http://snomed.info/sct', '300948004', 'Quadriceps weakness (finding)')
,('http://snomed.info/sct', '309249007', 'Calf muscle weakness (finding)')
,('http://snomed.info/sct', '309257005', 'Excessive weight loss (finding)')
,('http://snomed.info/sct', '312444006', 'Spastic paraparesis (finding)')
,('http://snomed.info/sct', '314109004', 'Feeling tired (finding)')
,('http://snomed.info/sct', '367391008', 'Malaise (finding)')
,('http://snomed.info/sct', '371028005', 'Spastic paresis (finding)')
,('http://snomed.info/sct', '373931001', 'Sensation of heaviness in limbs (finding)')
,('http://snomed.info/sct', '394616008', 'Unsteady gait (finding)')
,('http://snomed.info/sct', '397776000', 'Festinating gait (finding)')
,('http://snomed.info/sct', '404904002', 'Frail elderly (finding)')
,('http://snomed.info/sct', '413121008', 'Dependent on helper pushing wheelchair (finding)')
,('http://snomed.info/sct', '41786007', 'Neurological muscle weakness (finding)')
,('http://snomed.info/sct', '422868009', 'Unexplained weight loss (finding)')
,('http://snomed.info/sct', '426977000', 'Recent weight loss (finding)')
,('http://snomed.info/sct', '428116008', 'Multifactorial gait problem (finding)')
,('http://snomed.info/sct', '428264009', 'Painful gait (finding)')
,('http://snomed.info/sct', '429091008', 'Dependence on biphasic positive airway pressure ventilation (finding)')
,('http://snomed.info/sct', '429487005', 'Dependence on continuous positive airway pressure ventilation (finding)')
,('http://snomed.info/sct', '43005009', 'Shuffling gait (finding)')
,('http://snomed.info/sct', '431524008', 'Abnormal gait due to impairment of balance (finding)')
,('http://snomed.info/sct', '432559006', 'Abnormal gait due to muscle weakness (finding)')
,('http://snomed.info/sct', '444932008', 'Dependence on ventilator (finding)')
,('http://snomed.info/sct', '4468000', 'Oppenheims gait (finding)')
,('http://snomed.info/sct', '448765001', 'Unintentional weight loss (finding)')
,('http://snomed.info/sct', '50314001', 'Partial bilateral paresis (finding)')
,('http://snomed.info/sct', '60631000119109', 'Dependence on home ventilator (finding)')
,('http://snomed.info/sct', '60651000119103', 'Dependence on continuous supplemental oxygen (finding)')
,('http://snomed.info/sct', '67141003', 'Antalgic gait (finding)')
,('http://snomed.info/sct', '69161000119103', 'Functional gait abnormality (finding)')
,('http://snomed.info/sct', '713512009', 'Muscle weakness of upper limb (finding)')
,('http://snomed.info/sct', '713514005', 'Muscle weakness of limb (finding)')
,('http://snomed.info/sct', '713568000', 'Occasionally tired (finding)')
,('http://snomed.info/sct', '713655003', 'Dependence on non-invasive ventilation (finding)')
,('http://snomed.info/sct', '78119002', 'Complete bilateral paresis (finding)')
,('http://snomed.info/sct', '78691002', 'Staggering gait (finding)')
,('http://snomed.info/sct', '788876001', 'Cachexia due to malignant neoplastic disease (finding)')
,('http://snomed.info/sct', '788900007', 'Dependence on artificial heart (finding)')
,('http://snomed.info/sct', '79021000119104', 'Dependence on aspirator (finding)')
,('http://snomed.info/sct', '79031000119101', 'Dependence on respirator (finding)')
,('http://snomed.info/sct', '8510008', 'Reduced mobility (finding)')
,('http://snomed.info/sct', '85711000119103', 'Stumbling due to lack of coordination (finding)')
,('http://snomed.info/sct', '89201000119106', 'Dependence on supplemental oxygen when ambulating (finding)')
,('http://snomed.info/sct', '89362005', 'Weight loss (finding)')
,('http://snomed.info/sct', '931000119107', 'Dependence on supplemental oxygen (finding)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R26.2', 'Difficulty in walking, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R26.89', 'Other abnormalities of gait and mobility')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R26.9', 'Unspecified abnormalities of gait and mobility')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R53.1', 'Weakness')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R53.81', 'Other malaise')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R54', 'Age-related physical debility')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R62.7', 'Adult failure to thrive')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R63.4', 'Abnormal weight loss')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R63.6', 'Underweight')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R64', 'Cachexia')
) AS t (system, code, display) ;