create or replace view htn__define_enc_telemed as select * from (values
('http://www.ama-assn.org/go/cpt', '98966', 'Telephone assessment and management service provided by a qualified nonphysician health care professional to an established patient, parent, or guardian not originating from a related assessment and management service provided within the previous 7 days nor leading to an assessment and management service or procedure within the next 24 hours or soonest available appointment. 5-10 minutes of medical discussion')
,('http://www.ama-assn.org/go/cpt', '98967', 'Telephone assessment and management service provided by a qualified nonphysician health care professional to an established patient, parent, or guardian not originating from a related assessment and management service provided within the previous 7 days nor leading to an assessment and management service or procedure within the next 24 hours or soonest available appointment. 11-20 minutes of medical discussion')
,('http://www.ama-assn.org/go/cpt', '98968', 'Telephone assessment and management service provided by a qualified nonphysician health care professional to an established patient, parent, or guardian not originating from a related assessment and management service provided within the previous 7 days nor leading to an assessment and management service or procedure within the next 24 hours or soonest available appointment. 21-30 minutes of medical discussion')
,('http://www.ama-assn.org/go/cpt', '99441', 'Telephone evaluation and management service by a physician or other qualified health care professional who may report evaluation and management services provided to an established patient, parent, or guardian not originating from a related E/M service provided within the previous 7 days nor leading to an E/M service or procedure within the next 24 hours or soonest available appointment. 5-10 minutes of medical discussion')
,('http://www.ama-assn.org/go/cpt', '99442', 'Telephone evaluation and management service by a physician or other qualified health care professional who may report evaluation and management services provided to an established patient, parent, or guardian not originating from a related E/M service provided within the previous 7 days nor leading to an E/M service or procedure within the next 24 hours or soonest available appointment. 11-20 minutes of medical discussion')
,('http://www.ama-assn.org/go/cpt', '99443', 'Telephone evaluation and management service by a physician or other qualified health care professional who may report evaluation and management services provided to an established patient, parent, or guardian not originating from a related E/M service provided within the previous 7 days nor leading to an E/M service or procedure within the next 24 hours or soonest available appointment. 21-30 minutes of medical discussion')
,('http://snomed.info/sct', '185317003', 'Telephone encounter (procedure)')
,('http://snomed.info/sct', '314849005', 'Telephone contact by consultant (procedure)')
,('http://snomed.info/sct', '386472008', 'Telephone consultation (procedure)')
,('http://snomed.info/sct', '386473003', 'Telephone follow-up (procedure)')
,('http://snomed.info/sct', '401267002', 'Telephone triage encounter (procedure)')
) AS t (system, code, display) ;